<?php

/*
  Main Drupal module for bos_feedback_form

  david 03 2024
  @file docroot/modules/custom/bos_components/modules/bos_feedback_form/bos_feedback_form.module

*/

use Drupal\Core\Render\Markup;
use Drupal\webform\Plugin\WebformHandlerInterface;

/**
 * Implements hook_theme().
 */
function bos_feedback_form_theme($existing, $type, $theme, $path) {

  return [
    'block__bos_feedback_form' => [
      'base hook' => "block",
      'template' => 'block--bos-feedback-form',
      'preprocess' => TRUE,
    ],
    'bos_feedback_form__webform_html_editor_markup' => [
      'base hook' => "webform_html_editor_markup",
      'template' => 'bos-feedback-form--webform-html-editor-markup',
      'preprocess' => TRUE,
    ]
  ];

}

/**
 * Implements hook_webform_handler().
 */
function bos_feedback_form_webform_handler() {
  $handlers = [
    'zencity_form_handler' => [
      'id' => 'zencity_form_handler',
      'label' => t('Zencity form handler'),
      'description' => t('Posts submission results to zencity.'),
      'class' => 'Drupal\bos_feedback_form\Plugin\WebformHandler\ZencityWebformHandler',
      'cardinality' => WebformHandlerInterface::CARDINALITY_SINGLE,
      'results_processing' => FALSE,
    ],
  ];

  return $handlers;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bos_feedback_form_theme_suggestions_webform_html_editor_markup_alter(array &$suggestions, array &$variables) {
  $suggestions[] = 'bos_feedback_form__webform_html_editor_markup';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_feedback_form_preprocess_webform_html_editor_markup(array &$variables) {
  if (!empty($variables["markup"]) && str_contains($variables["markup"]->__toString(), "[close-button]")) {
    $variables["has_close_button"] = TRUE;
    $body = str_replace("[close-button]", "", $variables["markup"]->__toString());
    $variables["markup"] = Markup::create($body);
    $variables["content"]["#markup"] = Markup::create($body);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_feedback_form_preprocess_block(&$variables) {
  if (($variables["configuration"]["provider"]??"") == "bos_feedback_form") {
    $variables["#attached"]["library"][] = "bos_feedback_form/bos_feedback_form_block";
  }
}
