export default [
  {
    "title": "Halstead Salem Station",
    "id": "11568201",
    "slug": "halstead-salem-station-0",
    "cardinalDirection": "north",
    "city": "Salem",
    "neighborhood": null,
    "streetAddress": "72 Flint Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568201-1",
        "count": 8,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1625,
        "priceRate": "monthly",
      },
      {
        "id": "11568201-2",
        "count": 5,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1777,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "2020-07-14",
    "type": "apt",
  },
  {
    "title": "Lodge at Foxborough",
    "id": "11568131",
    "slug": "lodge-foxborough-0",
    "cardinalDirection": "south",
    "city": "Foxborough",
    "neighborhood": null,
    "streetAddress": "400 Foxborough Blvd.",
    "offer": "rent",
    "units": [
      {
        "id": "11568131-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1424,
        "priceRate": "monthly",
      },
      {
        "id": "11568131-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1694,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Hanover Westford Hills",
    "id": "11568166",
    "slug": "hanover-westford-hills-0",
    "cardinalDirection": "north",
    "city": "Westborough",
    "neighborhood": null,
    "streetAddress": "1 Westford Hills Road",
    "offer": "rent",
    "units": [
      {
        "id": "11568166-1",
        "count": 15,
        "amiQualification": 50,
        "bedrooms": 1,
        "price": 840,
        "priceRate": "monthly",
      },
      {
        "id": "11568166-2",
        "count": 17,
        "amiQualification": 50,
        "bedrooms": 2,
        "price": 975,
        "priceRate": "monthly",
      },
      {
        "id": "11568166-3",
        "count": 4,
        "amiQualification": 50,
        "bedrooms": 3,
        "price": 1097,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "2020-07-21",
    "type": "apt",
  },
  {
    "title": "467 Main Street",
    "id": "11568196",
    "slug": "467-main-street-0",
    "cardinalDirection": "west",
    "city": "Reading",
    "neighborhood": null,
    "streetAddress": "467 Main Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568196-1",
        "count": 4,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1515,
        "priceRate": "monthly",
      },
      {
        "id": "11568196-2",
        "count": 4,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1660,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Mattapan Heights III",
    "id": "11568126",
    "slug": "mattapan-heights-iii-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Mattapan",
    "streetAddress": "249 River St",
    "offer": "rent",
    "units": [
      {
        "id": "11568126-1",
        "count": 1,
        "amiQualification": 30,
        "bedrooms": 1,
        "price": 651,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "71 Topliff Street",
    "id": "11568226",
    "slug": "71-topliff-street-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Dorchester",
    "streetAddress": "71 Topliff Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568226-1",
        "count": 3,
        "amiQualification": 120,
        "bedrooms": 3,
        "price": 3200,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "multi-family",
  },
  {
    "title": "The Coolidge at Sudbury Phase 2",
    "id": "11568161",
    "slug": "coolidge-sudbury-phase-2-0",
    "cardinalDirection": "west",
    "city": "Sudbury",
    "neighborhood": null,
    "streetAddress": "189 Boston Post Road",
    "offer": "rent",
    "units": [
      {
        "id": "11568161-1",
        "count": 12,
        "amiQualification": 30,
        "bedrooms": 1,
        "price": null,
        "priceRate": "monthly",
      },
      {
        "id": "11568161-2",
        "count": 44,
        "amiQualification": 60,
        "bedrooms": 1,
        "price": 1165,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "2020-06-20",
    "type": "apt",
  },
  {
    "title": "660 Washington Apartments",
    "id": "11568191",
    "slug": "660-washington-apartments-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Chinatown",
    "streetAddress": "660 Washington Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568191-1",
        "count": 1,
        "amiQualification": 120,
        "bedrooms": 1,
        "price": 1876,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Medfield Meadows",
    "id": "11568121",
    "slug": "medfield-meadows-0",
    "cardinalDirection": "west",
    "city": "Medfield",
    "neighborhood": null,
    "streetAddress": "41 Dale Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568121-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1660,
        "priceRate": "monthly",
      },
      {
        "id": "11568121-2",
        "count": 4,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1825,
        "priceRate": "monthly",
      },
      {
        "id": "11568121-3",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 3,
        "price": 2002,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "2020-06-15",
    "type": "apt",
  },
  {
    "title": "660 Main Street",
    "id": "11568221",
    "slug": "660-main-street-0",
    "cardinalDirection": "south",
    "city": "Brockton",
    "neighborhood": null,
    "streetAddress": "660 Main Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568221-1",
        "count": 1,
        "amiQualification": null,
        "bedrooms": 3,
        "price": 1850,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": false,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "multi-family",
  },
  {
    "title": "The Point at Marlborough",
    "id": "11568156",
    "slug": "point-marlborough-0",
    "cardinalDirection": "west",
    "city": "Marlborough",
    "neighborhood": null,
    "streetAddress": "21 Austen Way",
    "offer": "rent",
    "units": [
      {
        "id": "11568156-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1360,
        "priceRate": "monthly",
      },
      {
        "id": "11568156-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1589,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "6 Lorne Street",
    "id": "11568186",
    "slug": "6-lorne-street-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Dorchester",
    "streetAddress": "6 Lorne Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568186-1",
        "count": 1,
        "amiQualification": 100,
        "bedrooms": 4,
        "price": 2500,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "multi-family",
  },
  {
    "title": "Modera",
    "id": "11568116",
    "slug": "modera-0",
    "cardinalDirection": "west",
    "city": "Framingham",
    "neighborhood": null,
    "streetAddress": "266 Waverly Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568116-1",
        "count": 2,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1404,
        "priceRate": "monthly",
      },
      {
        "id": "11568116-2",
        "count": 10,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1577,
        "priceRate": "monthly",
      },
      {
        "id": "11568116-3",
        "count": 12,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1736,
        "priceRate": "monthly",
      },
      {
        "id": "11568116-4",
        "count": 3,
        "amiQualification": 80,
        "bedrooms": 3,
        "price": 1889,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "2020-06-23",
    "type": "apt",
  },
  {
    "title": "275 Roxbury Street",
    "id": "11568216",
    "slug": "275-roxbury-street-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Roxbury",
    "streetAddress": "275 Roxbury Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568216-1",
        "count": 1,
        "amiQualification": 30,
        "bedrooms": 1,
        "price": 1270,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Print Lofts",
    "id": "11568151",
    "slug": "print-lofts-0",
    "cardinalDirection": "south",
    "city": "Norwood",
    "neighborhood": null,
    "streetAddress": "129 Guild Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568151-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1445,
        "priceRate": "monthly",
      },
      {
        "id": "11568151-2",
        "count": 8,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1625,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "735 Harrison Ave",
    "id": "11568181",
    "slug": "735-harrison-ave-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "South End",
    "streetAddress": "735 Harrison Ave",
    "offer": "sale",
    "units": [
      {
        "id": "11568181-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 327219,
        "priceRate": "once",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "347 West 2nd Street",
    "id": "11568211",
    "slug": "347-west-2nd-street-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "South Boston",
    "streetAddress": "347 West 2nd Street",
    "offer": "sale",
    "units": [
      {
        "id": "11568211-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 5,
        "price": 635580,
        "priceRate": "once",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "multi-family",
  },
  {
    "title": "The Viridian",
    "id": "11568141",
    "slug": "viridian-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Fenway",
    "streetAddress": "1282 Boylston Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568141-1",
        "count": 1,
        "amiQualification": 120,
        "bedrooms": 3,
        "price": 2947,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Avenu at Natick",
    "id": "11568176",
    "slug": "avenu-natick-0",
    "cardinalDirection": "west",
    "city": "Natick",
    "neighborhood": null,
    "streetAddress": "3 Superior Drive",
    "offer": "rent",
    "units": [
      {
        "id": "11568176-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1465,
        "priceRate": "monthly",
      },
      {
        "id": "11568176-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1657,
        "priceRate": "monthly",
      },
      {
        "id": "11568176-3",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1836,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "404 West 1st Street",
    "id": "11568206",
    "slug": "404-west-1st-street-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "South Boston",
    "streetAddress": "404 West 1st Street",
    "offer": "sale",
    "units": [
      {
        "id": "11568206-1",
        "count": 1,
        "amiQualification": 120,
        "bedrooms": 2,
        "price": 403891,
        "priceRate": "once",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "condo",
  },
  {
    "title": "The Beverly",
    "id": "11568136",
    "slug": "beverly-0",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "North End",
    "streetAddress": "101 Beverly Street",
    "offer": "rent",
    "units": [
      {
        "id": "11568136-1",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 0,
        "price": 2412,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-2",
        "count": 1,
        "amiQualification": 150,
        "bedrooms": 0,
        "price": 2650,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-3",
        "count": 1,
        "amiQualification": 165,
        "bedrooms": 0,
        "price": 2850,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-4",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 1,
        "price": 2646,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-5",
        "count": 1,
        "amiQualification": 150,
        "bedrooms": 1,
        "price": 2945,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-6",
        "count": 1,
        "amiQualification": 165,
        "bedrooms": 1,
        "price": 3195,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-7",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 2,
        "price": 3470,
        "priceRate": "monthly",
      },
      {
        "id": "11568136-8",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 3,
        "price": 4000,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Emery Flats",
    "id": "11568171",
    "slug": "emery-flats-0",
    "cardinalDirection": "north",
    "city": "Woburn",
    "neighborhood": null,
    "streetAddress": "200 Presidential Way",
    "offer": "rent",
    "units": [
      {
        "id": "11568171-1",
        "count": 2,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1446,
        "priceRate": "monthly",
      },
      {
        "id": "11568171-2",
        "count": 2,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1535,
        "priceRate": "monthly",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-06-02T13:00:01Z",
    "applicationDueDate": "",
    "type": "apt",
  },
];
