<?php

/**
 * @file
 * Contains functions to alter Drupal's markup for the adminimal theme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function bos_admin_preprocess_html(&$variables) {

  // Add adminimal class to the body.
  $variables['attributes']['class'][] = 'bos_admin';

}

/**
 * Implements hook_form_alter().
 */
function bos_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
}
