<?php

/*
  Main Drupal module for node_project

  david 08 2024
  @file docroot/modules/custom/bos_content/modules/node_project/node_project.module

*/

use Drupal\bos_geocoder\Controller\BosGeocoderController;
use Drupal\bos_geocoder\Utility\BosGeoAddress;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Form\FormStateInterface;

function node_project_theme() {
  return [
    'node__project' => [
      'render element' => 'elements',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_project_preprocess_form(&$variables) {
}

/**
 * Implements hook_form_alter().
 */
function node_project_form_node_project_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $ajax = [
    "callback" => '_ajax_cb_geocode',
    "event" => "click",
    "wrapper" => "edit-field-project-address-geolocatio-0-lat",
    'progress' => [
      'type' => 'throbber',
      'message' => t('Fetching Geocode data...'),
    ]
  ];
  $form['field_project_address']['widget'][0]['geo'] = [
    '#type'   => 'button',
    '#value'  => t('Fetch Geo-data'),
    '#name'   => 'field_address_ajax_submit',
    '#ajax'   => $ajax,
    '#prefix' => '<div id="edit-field-address-wrapper">',
    '#suffix' => '</div>',
  ];
  $form['field_project_address']['widget'][0]['geotxt'] = [
    '#markup' => "<div id='geotxt' style='display:none'></div>",
  ];
}

function _ajax_cb_geocode(array $form, FormStateInterface $form_state) {

  $response = new AjaxResponse();
  $address = $form_state->getUserInput()["field_project_address"][0]['address'] ?? [];
  $neighborhood = $form_state->getUserInput()["field_single_neighborhood"] ?? "_none";

  if ($address["address_line1"] == "" || $address["postal_code"] == "") {
    $response->addCommand(new HtmlCommand(
      '#geotxt',
      "<div id='geotxt'>Error: To fetch a GIS locator, an address and zipcode are required.</div>"
    ));
  }
  else {
    $_address = new BosGeoAddress(
      address: $address["address_line1"] . " " . $address["address_line2"] ?? "",
      neighborhood: $neighborhood == "_none" ? "" : $neighborhood,
      zip: $address["postal_code"] ?? "",
      country: $address["country_code"]
    );
    $geo = new BosGeocoderController($_address);
    $result = $geo->geocode($geo::AREA_BOSTON_ONLY);
    $response->addCommand(new InvokeCommand(
      '#edit-field-project-address-geolocatio-0-lat',
      "val",
      [$result->location()->lat()]
    ));
    $response->addCommand(new InvokeCommand(
      '#edit-field-project-address-geolocatio-0-lng',
      "val",
      [$result->location()->long()]
    ));

  }
  return $response;
}
