adding:
  dependencies:
    module:
      - masquerade
  permissions:
    140: 'masquerade as content_author'
    141: 'masquerade as content_editor'
    142: 'masquerade as content_reviewer'
removing: {  }
