<?php

/**
 * @file
 * Provides an emergency alert entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\core\Template\Attribute;
use Drupal\Core\Entity\EntityInterface;
/**
 * Implements hook_theme().
 */
function node_emergency_alert_theme() {
  return [
    'emergency_alert' => [
      'render element' => 'elements',
    ],
    'node__emergency_alert' => [
      'render element' => 'elements',
      'base hook' => 'node',
    ],
    'block__views_block__emergency_alerts_block_emergency_alert' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_emergency_alert_preprocess_form_element(&$variables) {
  if (isset($variables["element"]["#bundle"]) && $variables["element"]["#bundle"] == "emergency_alert") {
    if (isset($variables["name"]) && $variables["name"] == "field_theme") {
      $variables["description"]["attributes"]->addClass("bos-boxed-content-t");
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_emergency_alert_preprocess_page(&$variables) {
  $variables['cob']['has_emergency_alert'] = FALSE;

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_emergency_alert_preprocess_node__emergency_alert(&$variables) {
  $variables["para_attributes"] = new Attribute();
  $variables["para_attributes"]->addClass("b");
  $variables["para_attributes"]->addClass("b--fw");
  $variables["para_attributes"]->addClass("b--cc");
  $variables["para_attributes"]->addClass("b--" . $variables["content"]["field_theme"][0]["#markup"]);
  $variables["#attached"]["library"][] = "node_emergency_alert/emergency_alert.call";
  $variables["bos_title"] = $variables["title"][0]["#context"]["value"];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_emergency_alert_preprocess_block(&$variables) {
  if (!isset($variables["content"]["#view"]->current_display) || (isset($variables["content"]["#view"]->current_display) && $variables["content"]["#view"]->current_display != "block_emergency_alert")) {
    return;
  }
  $variables["attributes"]["class"][] = "page-wa";
  $variables["attributes"]["id"] = "page";
  // Ensure there is no label.
  unset($variables["label"]);
}

/**
 * Prepares variables for emergency alert templates.
 *
 * Default template: emergency-alert.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the emergency alert information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_node__emergency_alert(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_entity_create().
 */
function node_emergency_alert_entity_create(EntityInterface $entity) {
  // This may be needed to intercept create events and add node 21
  // (homepage to show_pages field).
}
