<?php

namespace Drupal\bos_metrolist\Plugin\views\style;

use Drupal\Core\Annotation\Translation;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Annotation\ViewsStyle;
use Drupal\views\Plugin\views\style\StylePluginBase;

/**
 * Unformatted style plugin to render rows one after another with no
 * decorations.
 *
 * @ingroup views_style_plugins
 *
 * @ViewsStyle(
 *   id = "metro_list_drawers_style",
 *   title = @Translation("MetroList Drawers"),
 *   help = @Translation("Displays rows one after another in Drawers."),
 *   theme = "views_view_metrolist_drawers",
 *   display_types = {"normal"}
 * )
 */
class MetroListDrawersStyle extends StylePluginBase {

  /**
   * {@inheritdoc}
   */
  protected $usesRowPlugin = TRUE;

  /**
   * Does the style plugin support custom css class for the rows.
   *
   * @var bool
   */
  protected $usesRowClass = TRUE;


  protected function defineOptions()
  {
    $options = parent::defineOptions(); // TODO: Change the autogenerated stub

    $options['show_email_button'] = ['default' => FALSE];
    $options['show_print_button'] = ['default' => FALSE];
    $options['show_all_units_button'] = ['default' => FALSE];

    $options['remove_duplicates'] = ['default' => FALSE];


    return $options;
  }


  public function buildOptionsForm(&$form, FormStateInterface $form_state)
  {
    parent::buildOptionsForm($form, $form_state); // TODO: Change the autogenerated stub

    $form['show_email_button'] = [
      '#title' => $this->t('Show Email Button'),
      '#description' => $this->t('Show Email Button'),
      '#type' => 'checkbox',
      '#default_value' => $this->options['show_email_button'],
    ];

    $form['show_print_button'] = [
      '#title' => $this->t('Show Print Button'),
      '#description' => $this->t('Show Print Button'),
      '#type' => 'checkbox',
      '#default_value' => $this->options['show_print_button'],
    ];

    $form['show_all_units_button'] = [
      '#title' => $this->t('Show All Units Button'),
      '#description' => $this->t('Show All Units Button'),
      '#type' => 'checkbox',
      '#default_value' => $this->options['show_all_units_button'],
    ];

    $form['remove_duplicates'] = [
      '#title' => $this->t('Remove Duplicates from parent view'),
      '#description' => $this->t('Remove Duplicates from parent view (Attachments Only)'),
      '#type' => 'checkbox',
      '#default_value' => $this->options['remove_duplicates'],
    ];


  }

}
