# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md

name: boston
recipe: drupal8

config:
  php: '7.3'
  webroot: 'docroot'
  database: mysql:5.7
  drush: 9
  xdebug: true
  drupal: false

services:
  node:
    type: node:10
    run:
      # this container builds after appserver, so in order to get useful info to the
      # console, print previously executed utilities here.
      - cat ${LANDO_MOUNT}/setup/uli.log && rm -f ${LANDO_MOUNT}/setup/uli.log
    globals:
      gulp-cli: "latest"

  # Database container.
  # Set default port mapping and default database credentials.
  database:
    type: mysql
    portforward: 3307
    host: localhost
    run_as_root:
      - apt-get update
      - apt-get install python-pip python-setuptools -y
      - pip install mycli
      - apt-get install wget ca-certificates -y
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - apt-get update
      - apt-get install pspg
    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    run_as_root:
      - /app/scripts/doit/lando-container-customize.sh

    run:
      - /app/scripts/doit/lando-build-drupal.sh

    xdebug: true

    config:
      conf: xdebug.ini

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
    - export PHP_IDE_CONFIG="serverName=boston.lndo.site" && export XDEBUG_CONFIG="remote_enable=true remote_host=10.0.0.74 idekey=PHPSTORM" && /app/vendor/bin/drush
#    - export PHP_IDE_CONFIG="serverName=boston.lndo.site" && export XDEBUG_CONFIG="remote_enable=true idekey=PHPSTORM remote_host=10.241.172.216" && /app/vendor/bin/drush
#    - /app/vendor/bin/drush

  drupal:
    service: appserver
    description: "Run drupal-console commands in app container: lando drupal <command>"
    cmd:
    - drupal

  npm:
    service: node
    description: "Run npm commands in node container: lando npm <command>"

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  phing:
    service: appserver
    description: "Run Phing tasks in app container: lando phing <task>"
    cmd:
      - /app/vendor/bin/phing

  mycli:
    service: database
    description: "Open mycli prompt in db container: lando mycli"
    cmd: "mycli -udrupal -pdrupal"

  drupal-sync-db:
    service: appserver
    description: "Drupal: Copy the remote staging DB into the local DB"
    cmd:
      - "/app/scripts/doit/sync.sh 'test'"

  drupal-pull-repo:
    service: appserver
    description: "Drupal: Pull the latest Drupal public and private repos from Git"
    cmd:
      - "/app/scripts/doit/pull.sh"

events:
  post-start:
    - echo "\033[1;32m[lando]\033[0m Docker containers are now started."
    - cd $LANDO_MOUNT && $LANDO_MOUNT/scripts/doit/branding.sh
