# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md
name: boston
recipe: drupal8
config:
  php: '8'
  webroot: docroot
  database: mysql:5.7
  xdebug: true
  drupal: false

proxy:
  node:
    - patterns.lndo.site
    - node.lndo.site:3443
    - cdn.lndo.site

services:
  node:
    type: node:10
    ssl: true
    scanner: false
    overrides:
      environment:
        PORT: "80"
        FRACTAL_PORT: "80"
        WEBAPP_PORT: "3443"
      healthcheck:
        test: /app/scripts/local/health.sh node
        interval: 30s
        timeout: 15s
        retries: 3
    build_as_root:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mbuild_as_root\e[0m Event raised on Container 'node'\n"
      - /app/scripts/local/lando-node-customize.sh
    run:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mrun\e[0m Event raised on Container 'node'\n"
      - /app/scripts/local/lando-build-node.sh
    command: /app/scripts/local/lando-node-post-start.sh

  database:
    type: mysql
    app_mount: false
    portforward: true
    host: localhost
    scanner: false
    overrides:
      ports:
        - "32306:3306"
      volumes:
        - ./scripts:/app/scripts
        - ./.lando.yml:/app/.lando.yml
      healthcheck:
        test: /helpers/health.sh database
        interval: 30s
        timeout: 10s
        retries: 3
    run_as_root:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mrun_as_root\e[0m Event raised on Container 'database'\n"
      - /app/scripts/local/lando-database-customize.sh
    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    type: php:8.0
    composer_version: '2-latest'
    webroot: docroot
    xdebug: debug
    scanner: false
    config:
      php: scripts/local/boston-dev-php.ini
    overrides:
      healthcheck:
        test: /app/scripts/local/health.sh appserver
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
        DRUSH_OPTIONS_URI: "https://boston.lndo.site"
        PHP_IDE_CONFIG: "serverName=boston.lndo.site"
        XDEBUG_CONFIG: "remote_enable=1 idekey=PHPSTORM client_port=9003"
    build_as_root:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mbuild_as_root\e[0m Event raised on Container 'appserver'\n"
      - /app/scripts/local/lando-appserver-customize.sh
    build:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mbuild\e[0m Event raised on Container 'appserver'\n"
    run:
      - printf "\e[1m\e[7m[LANDO]\e[0m \e[1mbuild as root\e[0m Event raised on Container 'appserver'\n"
      - /app/scripts/local/lando-build-drupal.sh -y

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
      - /app/vendor/bin/drush

  drupal:
    service: appserver
    description: "Run drupal-console commands in app container: lando drupal <command>"
    cmd:
      - drupal

  npm:
    service: node
    description: "Run npm commands in node:node container: lando npm <command>"

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  mycli:
    service: database
    description: "Open mycli prompt in db container: lando mycli"
    cmd: "mycli -udrupal -pdrupal"

  drupal-sync-db:
    service: appserver
    description: "Drupal: Copy the remote staging DB into the local DB"
    cmd:
      - /app/scripts/local/sync.sh 'dev'

  drupal-sync-files:
    service: appserver
    description: "Drupal: Copy the images and pdfs from prod to local"
    cmd:
      - /app/scripts/local/filesync.sh 'dev'

  drupal-pull-repo:
    service: appserver
    description: "Drupal: Pull the latest Drupal public and private repos from Git"
    cmd:
      - /app/scripts/local/pull.sh

  validate:
    service: appserver
    description: "Run the Linting and PHPCS routines on the current branch."
    cmd:
      - /app/scripts/local/validate.sh all

  switch-patterns:
    service: appserver
    description: "Switch the patterns library: 2 = local, 3 = prod, 4 = stage."
    cmd:
      - /app/vendor/bin/drush drush bcss

events:
  post-start:
    - appserver: printf "\e[1m\e[7m[LANDO]\e[0m \e[1mpost-start\e[0m Event raised on Container 'appserver'\n" && /app/scripts/local/lando-drupal-post-start.sh
