# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md

name: boston
recipe: drupal8

config:
  php: '7.3'
  webroot: 'docroot'
  database: mysql:5.7
  drush: 9
  xdebug: true
  drupal: false

services:
  node:
    type: node:10
    globals:
      gulp-cli: "latest"

  database:
    type: mysql
    portforward: 3307
    host: localhost
    run_as_root:
      - /app/scripts/local/lando-database-customize.sh
      -
    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    run_as_root:
      - /app/scripts/local/lando-appserver-customize.sh

    run:
      - /app/scripts/local/lando-build-drupal.sh

    xdebug: true

    overrides:
      # For PHPStorm editors.
      PHP_IDE_CONFIG="serverName=boston.lndo.site"
      # For XDebug of php from the cli (e.g. Drush & Composer)
      XDEBUG_CONFIG="remote_enable=1 remote_host=10.0.0.74 idekey=PHPSTORM"

    config:
      conf: xdebug.ini

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
    - /app/vendor/bin/drush -

  drupal:
    service: appserver
    description: "Run drupal-console commands in app container: lando drupal <command>"
    cmd:
    - drupal

  npm:
    service: node
    description: "Run npm commands in node container: lando npm <command>"

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  phing:
    service: appserver
    description: "Run Phing tasks in app container: lando phing <task>"
    cmd:
      - /app/vendor/bin/phing

  mycli:
    service: database
    description: "Open mycli prompt in db container: lando mycli"
    cmd: "mycli -udrupal -pdrupal"

  drupal-sync-db:
    service: appserver
    description: "Drupal: Copy the remote staging DB into the local DB"
    cmd:
      - /app/scripts/local/sync.sh 'test'

  drupal-pull-repo:
    service: appserver
    description: "Drupal: Pull the latest Drupal public and private repos from Git"
    cmd:
      - /app/scripts/local/pull.sh

events:
  post-start:
    - printf "\n\n==========================================================.\n"
    - printf "\033[1;32m[lando]\033[0m Docker containers are now started.\n"
    - cat ${LANDO_MOUNT}/setup/uli.log && rm -f ${LANDO_MOUNT}/setup/uli.log
