# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md

name: boston
recipe: drupal8
#proxy:
#  nginx:
#  edge:
#    - edge.acquia.lndo.site

config:
  php: '7.1'
  webroot: 'docroot'
  database: mysql:5.7
  drush: composer
  xdebug: true
  drupal: false

services:
  node:
    type: node:8.9

    run:
      - cd /app && ./scripts/doit/branding.sh
      - echo "\033[1;33mUse the following link to login to the site as administrator.\033[0m"
      - cat /app/setup/.uli && rm -f /app/setup/.uli

    globals:
      gulp-cli: "latest"

  # Database container.
  # Set default port mapping and default database credentials.
  database:
    type: mysql
    portforward: 3307
    host: localhost
    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    composer:
        # Loads Phing initially into the container so the startup process can carry on builds with Phing.
        # Phing is then also referenced in composer.json to ensure it is loaded into the right
        # vendor folder for the project.
        "phing/phing": "2.*"

    run_as_root:
      - echo "\033[1;33m> Verify linux packages in appserver container...\033[0m"
      - apt-get update -y  > ${LANDO_MOUNT}/setup/.lando.log
      # Installs linux apps and extensions into the appserver container.
      - apt-get install -y --no-install-recommends apt-utils zip unzip bzip2 libbz2-dev libgd-dev mysql-client openssh-client vim jq >> ${LANDO_MOUNT}/setup/.lando.log
      - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ >> ${LANDO_MOUNT}/setup/.lando.log
      # Change the permissions on the log file so that non-root user can add to log.
      - chmod 777 ${LANDO_MOUNT}/setup/.lando.log >> ${LANDO_MOUNT}/setup/.lando.log
      # [Optional] Do not need the next 2 statements on stage or production servers
      - cp /app/scripts/phing/files/xdebug.ini /usr/local/etc/php/conf.d/boston.xdebug.ini
      - printf "\nxdebug.remote_host=${LANDO_HOST_IP}\n" >>/usr/local/etc/php/conf.d/boston.xdebug.ini

    run:
      - echo "\033[1;33m> Verify Drupal and dependencies are installed in appserver & database containers...\033[0m"
      # Next command creates a link to enable a cli alias for phing.
      - if [ ! -e  /usr/local/bin/phing ]; then ln -s ${LANDO_MOUNT}/vendor/phing/phing/bin/phing /usr/local/bin/ >> ${LANDO_MOUNT}/setup/.lando.log; fi
      # Next command hands off to Phing to complete the initial setup.
#      - cd $LANDO_MOUNT && phing setup:docker:drupal-local
      # Now setup the node container.
      - echo "\033[1;33m> Verify linux node library/extensions in node container...\033[0m"

    overrides:
      services:
        environment:
          LANDO_INFO: LANDO_INFO
          PHP_IDE_CONFIG: 'serverName=lando'
          XDEBUG_CONFIG: 'idekey=PHPSTORM'

  # set up a Varnish edge
#  edge:
#    type: varnish:4.1
#    backends:
#      - appserver
#    ssl: true
#
#  cache:
#    type: memcached:2.2

proxy:
  appserver:
    - boston.lndo.site

tooling:

  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
      - drush

  npm:
    service: node
    description: "Run npm commands in node container: lando npm <command>"

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  phing:
    service: appserver
    description: "Run Phing tasks in app container: lando phing <task>"
    cmd:
      - phing

  # Add in routes to the varnish cli tools
#  varnishadm:
#    service: edge
#    user: root
#  varnishstat:
#    service: edge
#    user: root
#  varnishlog:
#    service: edge
#    user: root

events:
  post-start:
    - echo "Containers started."
    - cd $LANDO_MOUNT && $LANDO_MOUNT/scripts/doit/branding.sh
    - if [ ! -d $LANDO_MOUNT/setup ]; then mkdir $LANDO_MOUNT/setup; fi
