# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md

name: boston
recipe: drupal8

config:
  php: '7.3'
  webroot: docroot
  database: mysql:5.7
  xdebug: true
  drupal: false

services:
  node:
    type: node:10
    globals:
      gulp-cli: "latest"
    build_as_root:
      - printf "\n[LANDO] Node Container Event - build as root\n\n"
      - /app/scripts/local/lando-node-customize.sh
    run:
      - printf "\n[LANDO] Node Container Event - run\n\n"
      - /app/scripts/local/lando-build-node.sh

  database:
    type: mysql
    portforward: true
    host: localhost
    run_as_root:
      - printf "\n[LANDO] Database Event - run as root\n\n"
      - /app/scripts/local/lando-database-customize.sh

    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    type: php:7.3
    webroot: docroot
    xdebug: true
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=boston.lndo.site"
        XDEBUG_CONFIG: "remote_enable=1 idekey=PHPSTORM remote_host=host.docker.internal"
    config:
      conf: xdebug.ini

    build_as_root:
      - printf "\n[LANDO] Appserver Event - build as root\n\n"
      - /app/scripts/local/lando-appserver-customize.sh

    build:
      - printf "\n[LANDO] Appserver Event - build\n\n"
      - /bin/sh -c "composer require drush/drush:^9 --no-update --no-progress --no-suggest --prefer-dist &> /dev/null"

    run:
      - printf "\n[LANDO] Appserver Event - run\n\n"
      - /app/scripts/local/lando-build-drupal.sh -y

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
    - /app/vendor/bin/drush

  drupal:
    service: appserver
    description: "Run drupal-console commands in app container: lando drupal <command>"
    cmd:
    - drupal

  npm:
    service: node
    description: "Run npm commands in node container: lando npm <command>"

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  mycli:
    service: database
    description: "Open mycli prompt in db container: lando mycli"
    cmd: "mycli -udrupal -pdrupal"

  drupal-sync-db:
    service: appserver
    description: "Drupal: Copy the remote staging DB into the local DB"
    cmd:
      - /app/scripts/local/sync.sh 'test'

  drupal-pull-repo:
    service: appserver
    description: "Drupal: Pull the latest Drupal public and private repos from Git"
    cmd:
      - /app/scripts/local/pull.sh

  validate:
    service: appserver
    description: "Run the Linting and PHPCS routines on the current branch."
    cmd:
      - /app/scripts/local/validate.sh all

events:
  post-start:
    - /app/scripts/local/lando-post-start.sh
