# Acquia friendly mods from https://github.com/lando/lando/issues/105
# See readme in ./build/readme.boston.md

name: boston
recipe: drupal8

config:
  php: '7.3'
  webroot: docroot
  database: mysql:5.7
  xdebug: true
  drupal: false

proxy:
  patterns:
    - patterns.lndo.site
    - node.lndo.site

services:
  node:
    type: node:10
    ssl: true
    overrides:
      expose:
        - "80"
        - "443"
      ports:
        - "80:3030"
      environment:
        PORT: "80"
        FRACTAL_PORT: "80"
      healthcheck:
        test: /app/scripts/local/health.sh node
        interval: 30s
        timeout: 15s
        retries: 5
    build_as_root:
      - printf "\n[LANDO] node Container Event - build as root\n"
      - /app/scripts/local/lando-node-customize.sh
    run:
      - printf "\n[LANDO] node Container Event - run\n\n"
      - /app/scripts/local/lando-build-node.sh
    command: /app/scripts/local/lando-node-post-start.sh

  database:
    type: mysql
    app_mount: false
    portforward: true
    host: localhost
    overrides:
      healthcheck:
        test: /helpers/health.sh database
        interval: 30s
        timeout: 10s
        retries: 5
    run_as_root:
      - printf "\n[LANDO] Database Event - run as root\n\n"
      - /helpers/lando-database-customize.sh

    creds:
      user: drupal
      password: drupal
      database: drupal

  appserver:
    type: php:7.3
    webroot: docroot
    xdebug: true
    overrides:
      healthcheck:
        test: /app/scripts/local/health.sh appserver
        interval: 30s
        timeout: 15s
        retries: 5
      environment:
        PHP_IDE_CONFIG: "serverName=boston.lndo.site"
        XDEBUG_CONFIG: "remote_enable=1 idekey=PHPSTORM"
    config:
      conf: xdebug.ini

    build_as_root:
      - printf "\n[LANDO] Appserver Event - build as root\n"
      - /app/scripts/local/lando-appserver-customize.sh

    build:
      - printf "\n[LANDO] Appserver Event - build\n\n"
      - /bin/sh -c "composer require drush/drush:^9 --no-update --no-progress --no-suggest --prefer-dist &> /dev/null"

    run:
      - printf "\n[LANDO] Appserver Event - run\n\n"
      - /app/scripts/local/lando-build-drupal.sh -y

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  drush:
    service: appserver
    description: "Run drush commands in app container: lando drush <command>"
    cmd:
    - /app/vendor/bin/drush

  drupal:
    service: appserver
    description: "Run drupal-console commands in app container: lando drupal <command>"
    cmd:
    - drupal

  npm:
    service: node
    description: "Run npm commands in node:node container: lando npm <command>"
    cmd:
      - echo a; cd /app/patterns && npm

  node:
    service: node
    description: "Run node commands in node container: lando node <command>"

  gulp:
    service: node
    description: "Run node:gulp commands in node container: lando gulp <command>"

  mycli:
    service: database
    description: "Open mycli prompt in db container: lando mycli"
    cmd: "mycli -udrupal -pdrupal"

  drupal-sync-db:
    service: appserver
    description: "Drupal: Copy the remote staging DB into the local DB"
    cmd:
      - /app/scripts/local/sync.sh 'dev'

  drupal-sync-files:
    service: appserver
    description: "Drupal: Copy the images and pdfs from prod to local"
    cmd:
      - /app/scripts/local/filesync.sh 'dev'

  drupal-pull-repo:
    service: appserver
    description: "Drupal: Pull the latest Drupal public and private repos from Git"
    cmd:
      - /app/scripts/local/pull.sh

  validate:
    service: appserver
    description: "Run the Linting and PHPCS routines on the current branch."
    cmd:
      - /app/scripts/local/validate.sh all

  switch-patterns:
    service: appserver
    description: "Switch the patterns library: 2 = local, 3 = prod, 4 = stage."
    cmd:
      - /app/vendor/bin/drush drush bcss

events:
  post-start:
    - appserver: /app/scripts/local/lando-drupal-post-start.sh
