<?php

/**
 * @file
 * Provides a site alert entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function site_alert_theme() {
  return [
    'site_alert' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for site alert templates.
 *
 * Default template: site-alert.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the site alert information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_site_alert(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
