<?php

/**
 * @file
 * Provides a node_post entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function node_post_theme() {
  return [
    'node__post' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_post_preprocess_page(&$variables) {
  if (isset($variables["node"]) && $variables["node"]->bundle() == "post") {
    $variables['header_image'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_post_preprocess_node__post(&$variables) {
  _bos_components_fix_attributes($variables);
  $variables['attributes']->addClass("desktop-100");
  $variables['attributes']->setAttribute("id", "node-" . $variables['elements']["#node"]->id() );
}

/**
 * Prepares variables for post templates.
 *
 * Default template: post.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the post information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_post(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

