<?php

/**
 * @file
 * Provides a node_post entity type.
 */

use Drupal\bos_core\BackgroundResponsiveImage;
use Drupal\Core\Render\Element;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function node_post_theme() {
  return [
    'node__post' => [
      'render element' => 'elements',
      'base hook' => 'node',
    ],
    'node__post__listing' => [
      'base' => 'node',
    ],
    'node__post__featured_item' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_post_preprocess_page(&$variables) {
  if (NULL != ($node = $variables["node"] ?? NULL)) {
    if (is_numeric($node)) {
      // $variables['node'] is the nid when a view_display version of the
      // page is rendered.
      return;
    }
    if ($node->bundle() == "post") {
      // Now make and render the Intro_image block.
      $variables['header_image'] = FALSE;
      if (isset($variables['content']['field_intro_image']) && $variables["node"]->get('field_intro_image')->count()) {
        $variables['header_image'] = TRUE;
        _bos_content_fix_attributes($variables);
        $variables["attributes"]->addClass("mn");
        $variables["attributes"]->setAttribute("id", "page");
        $nestedElement = [
          ["div" => "b b--fw b--fw--480"],
          ["div" => $variables['photo_id'] . " hro hro--pt hro--pb"],
        ];
        $variables["content"]["intro_image"] = BackgroundResponsiveImage::createBackgroundFramework($nestedElement);
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_post_preprocess_node__post(&$variables) {
  _bos_components_fix_attributes($variables);
  $variables['attributes']->addClass("desktop-100");
  $variables['attributes']->setAttribute("id", "node-" . $variables['elements']["#node"]->id());
}

/**
 * Implements hook_rebuild().
 */
function node_post_rebuild() {
  // Install the default background image.
  // Copy rather than move so we dont get git issues.
  $modName = basename(__FILE__, ".module");
  $modulePath = drupal::root() . '/' . drupal_get_path("module", $modName);
  $path = drupal::root() . "/sites/default/files/img/post/";
  $destName = "default_news.svg";
  if (!file_exists($path)) {
    mkdir($path, 0777);
  }
  if (file_exists($path . $destName)) {
    unlink($path . $destName);
  }
  copy($modulePath . "/default_news.svg", $path . $destName);

  // Check if the file exists that is listed in para.para_type.module.yml.
  $filesystem = \Drupal::service('file_system');
  $entity = str_replace("bos_", "", $modName);
  $mod = \Drupal::entityTypeManager()
    ->getStorage("paragraphs_type")->load($entity);
  if (!empty($mod)) {
    $destination = "public://img/post/" . $destName;
    $image = Drupal::entityTypeManager()->getStorage("file")
      ->loadByProperties(["uri" => $destination]);
    if (count($image) == 0) {
      $image = File::create();
      $image->setFileUri($destination);
      $image->setOwnerId(\Drupal::currentUser()->id());
      $image->setMimeType('image/' . pathinfo($destination, PATHINFO_EXTENSION));
      $image->setFileName($filesystem->basename($destination));
      $image->setPermanent();
      $image->save();
    }
  }
}

/**
 * Prepares variables for post templates.
 *
 * Default template: post.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the post information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 *
 * @throws \Exception
 */
function template_preprocess_node__post(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Handle intro_image if present.
  // Has to happen in this template_preprocess_hook or does not #attach(ed).
  if (isset($variables['content']['field_intro_image'])) {
    $background_image = $variables["elements"]["field_intro_image"];
    switch ($variables["elements"]["#view_mode"]) {
      case "featured_item":
        break;

      case "listing":
        break;

      default:
        if (isset($background_image["#items"]) && $background_image["#items"]->count()) {
          $photo_id = Html::getUniqueId('hro');
          $variables['photo_id'] = $photo_id;
          $css = BackgroundResponsiveImage::createBackgroundCss($background_image, ".$photo_id");
          $variables['#attached']['html_head'][] = [
            [
              "#tag" => "style",
              "#value" => $css,
              "#weight" => 100,
            ],
            'post-intro-image-css-' . $photo_id,
          ];
        }
    }
  }

}
