<?php

/**
 * @file
 * The Base module file for bos_events_and_notices module.
 */

/**
 * Implements hook_theme().
 */
function bos_events_and_notices_theme() {
  $theme['paragraph__events_and_notices'] = [
    'base hook' => 'paragraph',
    'path' => drupal_get_path('module', 'bos_events_and_notices') . '/templates',
  ];
  $theme['views_view_unformatted__events_and_notices'] = [
    'base hook' => 'view',
    'path' => drupal_get_path('module', 'bos_events_and_notices') . '/templates',
  ];
  $theme['views_view_fields__events_and_notices'] = [
    'base hook' => 'view',
    'path' => drupal_get_path('module', 'bos_events_and_notices') . '/templates',
  ];
  $theme['viewfield__paragraph__events_and_notices'] = [
    'base hook' => 'viewfield',
    'path' => drupal_get_path('module', 'bos_events_and_notices') . '/templates',
  ];
  return $theme;
}
