<?php

/**
 * @file
 * The Base module file for bos_events_and_notices module.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\Sql;

/**
 * Implements hook_theme().
 */
function bos_events_and_notices_theme() {
  $theme['paragraph__events_and_notices'] = [
    'base hook' => 'paragraph',
  ];
  $theme['field__paragraph__field_link__events_and_notices'] = [
    'base hook' => 'field',
  ];
  $theme['views_view_unformatted__events_and_notices'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices'] = [
    'base hook' => 'view',
  ];
  $theme['viewfield__paragraph__events_and_notices'] = [
    'base hook' => 'viewfield',
  ];
  $theme['views_view_fields__events_and_notices__upcoming_small'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__upcoming_medium'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__upcoming_large'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__large_attachment'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__medium_attachment'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__related_attachment_large'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__referenced_large_attachment'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__related_attachment_medium'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__referenced_medium_attachment'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__upcoming_auto'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__related_auto'] = [
    'base hook' => 'view',
  ];
  $theme['views_view_fields__events_and_notices__referenced_auto'] = [
    'base hook' => 'view',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK__bundle().
 */
function bos_events_and_notices_preprocess_paragraph__events_and_notices(&$variables) {
  $variables["classes"] = "entity entity-paragraphs-item paragraphs-item-events-and-notices component-section fullwidth";
}

/**
 * Implements hook_preprocess_views_view_fields().
 */
function bos_events_and_notices_preprocess_views_view_fields__events_and_notices(&$variables) {
  if ($node = $variables["row"]->_entity) {
    $type = $node->getType();
    $variables['type_class'] = 'news-item-' . $type;

    $fields = $variables["fields"];

    if ($node->hasField("field_thumbnail") && $node->get("field_thumbnail")->target_id) {
      $variables["thumbnail"] = $fields["field_thumbnail"]->content;
    }
    elseif ($node->hasField("field_intro_image") && $node->get("field_intro_image")->target_id) {
      $variables["thumbnail"] = $fields["field_intro_image"]->content;
    }

    if ($node->hasField("field_phone_number") && $node->get("field_phone_number")->value) {

      if (!empty($fields["field_phone_number"])) {
        $variables["phone"] = $fields["field_phone_number"]->content;
      }
    }

    if ($node->hasField("field_cost") && $node->get("field_cost")->value) {

      if (!empty($fields["field_cost"])) {
        $variables["cost"] = $fields["field_cost"]->content;
      }
    }

    if ($node->hasField("field_public_notice_date") && $node->get("field_public_notice_date")->value) {
      $variables["date_recur"] = strip_tags(str_replace("\n", "", $fields["field_public_notice_date"]->content));
    }
    elseif ($node->hasField("field_event_date_recur") && $node->get("field_event_date_recur")->value) {
      if (!empty($fields["field_event_date_recur_value"]) && $fields["field_event_date_recur_value"]->raw) {
        $variables["date_recur"] = strip_tags(str_replace("\n", "", $fields["field_event_date_recur_value"]->content));
      }
      else {
        $variables["date_recur"] = strip_tags(str_replace("\n", "", $fields["field_event_date_recur"]->content));
      }
    }

    if (isset($variables["date_recur"])) {
      // Force into the boston featured date format.
      $variables["date_recur"] = \Drupal::service('date.formatter')->format(strtotime($variables["date_recur"]), "date_format_boston_featured");
    }

    if ($node->hasField("field_public_notice_date") && $node->get("field_public_notice_date")->value) {
      $start_date = "";
      if (isset($node->get("field_public_notice_date")->value)) {
        $start_date = $node->get("field_public_notice_date")->value;
        if (is_string($start_date)) {
          $start_date = new DateTime($start_date . "+0000");
          $start_date->setTimezone(new DateTimeZone("America/new_york"));
        }
        $stdt = $start_date->format("F d, Y, g:iA");
        $edt = "";
      }
      if (isset($node->get("field_public_notice_date")->end_value)) {
        $end_date = $node->get("field_public_notice_date")->end_date;
        $end_date->setTimezone(new DateTimeZone("America/new_york"));
        if ($start_date->format("ymd") == $end_date->format("ymd")) {
          if ($start_date->format("g:iA") != $end_date->format("g:iA")) {
            $edt = $end_date->format(" - g:iA");
          }
        }
        else {
          $edt = " to " . $end_date->format("F d, Y, g:iA");
        }
      }
      $variables["dates"] = $stdt . $edt;
    }
    elseif ($node->hasField("field_event_date_recur") && $node->get("field_event_date_recur")->value) {
      if (!empty($fields["field_event_date_recur_value"]) && $fields["field_event_date_recur_value"]->raw) {
        $start_date = "";
        if (isset($node->get("field_event_date_recur")->value)) {
          $start_date = $fields["field_event_date_recur_value"]->raw;
          if (is_string($start_date)) {
            $start_date = new DateTime($start_date . "+0000");
            $start_date->setTimezone(new DateTimeZone("America/new_york"));
          }
          $stdt = $start_date->format("F d, Y, g:i A");
          $edt = "";
        }
        if (isset($node->get("field_event_date_recur")->end_value)) {
          $end_date = $node->get("field_event_date_recur")->end_date;
          $end_date->setTimezone(new DateTimeZone("America/new_york"));
          if ($start_date->format("ymd") == $end_date->format("ymd")) {
            if ($start_date->format("g:i A") != $end_date->format("g:i A")) {
              $edt = $end_date->format(" - g:i A");
            }
          }
          else {
            $edt = $end_date->format("F d, Y, g:i A");
          }
        }
        $variables["dates"] = $stdt . $edt;
      }
    }

    $variables["event_link"] = strip_tags(trim(str_replace("\n", "", $fields["view_node"]->content)));
  }
}

/**
 * Implements hook_views_pre_build().
 */
function bos_events_and_notices_views_pre_build(ViewExecutable $view) {
  if ($view->id() == "news_and_announcements") {
    $view->setShowAdminLinks(FALSE);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function bos_events_and_notices_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'events_and_notices' && ($view->getDisplay()->display['id'] == 'upcoming_auto')) {
    $result_count = count($view->result);
    //Show large cards
    if ($result_count == 1){
      unset($view->attachment_before[1]);
      $view->result = [];
      $view->empty = [];
    }
    //show medium cards
    elseif ($result_count > 1 && $result_count < 4) {
      unset($view->attachment_before[0]);
      $view->result = [];
      $view->empty = [];
    }
    else {
      //show small cards
      unset($view->attachment_before[0]);
      unset($view->attachment_before[1]);
    }
  }

  if ($view->id() == 'events_and_notices' && ($view->getDisplay()->display['id'] == 'related_auto')) {
    $result_count = count($view->result);
    //Show large cards
    if ($result_count == 1){
      unset($view->attachment_before[1]);
      $view->result = [];
      $view->empty = [];
    }
    //show medium cards
    elseif ($result_count > 1 && $result_count < 4) {
      unset($view->attachment_before[0]);
      $view->result = [];
      $view->empty = [];
    }
    else {
      //show small cards
      unset($view->attachment_before[1]);
      unset($view->attachment_before[0]);
    }
  }

  if ($view->id() == 'events_and_notices' && ($view->getDisplay()->display['id'] == 'referenced_auto')) {
    $result_count = count($view->result);
    //Show large cards
    if ($result_count == 1){
      unset($view->attachment_before[1]);
      $view->result = [];
      $view->empty = [];
    }
    //show medium cards
    elseif ($result_count > 1 && $result_count < 4) {
      unset($view->attachment_before[0]);
      $view->result = [];
      $view->empty = [];
    }
    else {
      //show small cards
      unset($view->attachment_before[1]);
      unset($view->attachment_before[0]);
    }
  }

}

/**
 * Implements hook_views_query_alter().
 */
function bos_events_and_notices_views_query_alter(ViewExecutable $view, Sql $query) {
  if ($view->id() == 'events_and_notices' && ($view->getDisplay()->display['id'] == 'upcoming' || $view->getDisplay()->display['id'] == 'related' || $view->getDisplay()->display['id'] == 'upcoming_small' || $view->getDisplay()->display['id'] == 'upcoming_medium' || $view->getDisplay()->display['id'] == 'upcoming_large' || $view->getDisplay()->display['id'] == 'upcoming_auto' || $view->getDisplay()->display['id'] == 'related_auto' || $view->getDisplay()->display['id'] == 'referenced_auto')) {
    $sql = "CASE
        WHEN node__field_public_notice_date.field_public_notice_date_value IS NOT NULL THEN node__field_public_notice_date.field_public_notice_date_value
        WHEN date_recur__node__field_event_date_recur_node_field_data.field_event_date_recur_value IS NOT NULL THEN date_recur__node__field_event_date_recur_node_field_data.field_event_date_recur_value
        ELSE node__field_event_date_recur.field_event_date_recur_value
    END";
    $query->addOrderBy(NULL, $sql, 'ASC', 'pub_or_event_date');
  }
}
