program_initiative_profile.program_initiative_profile_type.*:
  type: config_entity
  label: 'Program Initiative Profile type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
