<?php

/**
 * @file
 * Provides a public notice entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function public_notice_theme() {
  return [
    'public_notice' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for public notice templates.
 *
 * Default template: public-notice.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the public notice information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_public_notice(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
