<?php

/**
 * @file
 * The Base module file for bos_photo module.
 */

use Drupal\bos_core\BackgroundResponsiveImage;
use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function bos_photo_theme() {
  $theme['paragraph__photo'] = [
    'base hook' => 'paragraph',
  ];
  $theme['field__paragraph__field_image__photo'] = [
    'base hook' => 'field',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_photo_preprocess_paragraph__photo(&$variables) {
  if (!empty($variables['paragraph'])) {
    $paragraph = $variables['paragraph'];
    if (!$paragraph->get('field_link')->isEmpty()) {
      $cta = _bos_core_paragraph_extract_link(
        $paragraph->get('field_link')->getValue(),
        ['class' => 'btn']
      );
      if (!empty($cta['link'])) {
        $variables['cta'] = $cta['link'];
      }
    }

    if ($paragraph->hasField('field_image') && $paragraph->get('field_image')->count()) {
      $nestedElement = [
        ["div" => "ph-p " . $variables['photo_id']],
      ];
      $variables["content"]["display_image"] = BackgroundResponsiveImage::createBackgroundFramework($nestedElement);
    }

  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function bos_photo_preprocess_paragraph(&$vars) {

}

/**
 * Implements hook_preprocess_field().
 */
function bos_photo_preprocess_field(&$vars) {
  switch ($vars['field_name']) {
    case 'field_photo_credit':
      $vars['label'] .= ':';
      break;

    case 'field_image':
      if (!empty($vars['element']['#object']->_photo_id)) {
        $image = $vars['element']['#object']->get('field_image')->getValue();
        $base_url = file_load($image['0']['target_id'])->getFileUri();
        $styles = [
          'xlarge_image' => 'rep_wide_2000x700custom_boston_desktop_2x',
          'large_image' => 'rep_wide_2000x700custom_boston_desktop_1x',
          'medium_image' => 'rep_wide_2000x700custom_boston_tablet_2x',
          'small_image' => 'rep_wide_2000x700custom_boston_mobile_2x',
        ];
        foreach ($styles as $name => $style) {
          $style = \Drupal::entityTypeManager()->getStorage('image_style')->load($style);
          $vars[$name] = $style->buildUrl($base_url);
        }
        $vars['photo_id'] = $vars['element']['#object']->_photo_id;
      }
      break;
  }
}

/**
 * Prepares variables for post templates.
 *
 * Default template: post.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the post information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_paragraph__photo(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Assign a unique id to this photo for the page.
  if (!empty($variables['paragraph'])) {
    $photo_id = Html::getUniqueId('ph-p--1');
    $variables['paragraph']->_photo_id = $photo_id;
    $variables['photo_id'] = $photo_id;
  }

  // Handle field_image if present.
  // Has to happen in this template_preprocess_hook or does not #attach(ed).
  if ($variables['paragraph']->hasField('field_image')) {
    $background_image = $variables['paragraph']->get('field_image');
    if ($background_image->count()) {
      $anchor_class = "." . $variables["photo_id"];
      $css = BackgroundResponsiveImage::createBackgroundCss($background_image, "hero", "photo_bleed_images", $anchor_class);
      $variables['#attached']['html_head'][] = [
        [
          "#tag" => "style",
          "#value" => $css,
          "#weight" => 100,
        ],
        'photo-image-css-' . $variables["photo_id"],
      ];
    }
  }

}
