<?php

/**
 * @file
 * The Base module file for bos_photo module.
 */

use Drupal\bos_core\BackgroundResponsiveImage;
use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Markup;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_theme().
 */
function bos_slideshow_theme() {
  $theme['paragraph__slideshow'] = [
    'base hook' => 'paragraph',
    'render element' => 'content'
  ];
  $theme['views_view__slick_carousel_default'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_slideshow/templates',
  ];
  return $theme;
}


/**
 * Implements hook_preprocess_HOOK().
 */
function bos_slideshow_preprocess_paragraph__slideshow(&$variables) {
  $variables["#attached"]["library"][] = "slick/slick";
  $variables["#attached"]["library"][] = "slick/base";
  $variables["#attached"]["library"][] = "slick/slick.load";
}
