<?php

/**
 * @file
 * The Base module file for bos_photo module.
 */

use Drupal\bos_core\BackgroundResponsiveImage;
use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Markup;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_theme().
 */
function bos_slideshow_theme() {
  $theme['paragraph__slideshow'] = [
    'base hook' => 'paragraph',
  ];
  return $theme;
}


/**
 * Implements hook_preprocess_HOOK().
 */
function bos_slideshow_preprocess_paragraph__slideshow(&$variables) {

  if (!empty($variables['paragraph'])) {

    $paragraph = $variables['paragraph'];

  }
}

/**
 * Prepares variables for post templates.
 *
 * Default template: post.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the post information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 *
 * @throws \Exception
 */
function template_preprocess_paragraph__slideshow(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

}
