#!/bin/bash

lando drush pmu bos_migration &&
lando drush config-delete migrate_plus.migration_group.bos_paragraphs &&
lando drush config-delete migrate_plus.migration_group.bos_taxonomy &&
lando drush config-delete migrate_plus.migration.paragraph__3_column_w_image &&
lando drush config-delete migrate_plus.migration.paragraph__bid &&
lando drush config-delete migrate_plus.migration.paragraph__bos311 &&
lando drush config-delete migrate_plus.migration.paragraph__bos_signup_emergency_alerts &&
lando drush config-delete migrate_plus.migration.paragraph__cabinet &&
lando drush config-delete migrate_plus.migration.paragraph__external_link &&
lando drush config-delete migrate_plus.migration.paragraph__list &&
lando drush config-delete migrate_plus.migration.taxonomy__311_request &&
lando drush en bos_migration

count="$(lando drush ms --group=bos_paragraphs | wc -l)"
if (( "$count" > 3 )); then

  lando drush ms --group=bos_paragraphs

else

  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  NC='\033[0m'

  echo $'\r'
  echo -e "${RED}### YOUR CONNECTION TO THE D7 DATABASE DOES NOT APPEAR TO BE WORKING! ${NC}"
  echo $'\r'
  echo -e "${RED}###${NC} Did you remember to ${GREEN}lando ssh${NC} into the appserver and run:"
  echo $'\r'
  echo -e "     ${YELLOW}ssh -i /user/.ssh/id_rsa -4 -L 3336:127.0.0.1:3306 boston.dev@staging-15139.prod.hosting.acquia.com -N${NC}"
  echo $'\r'
  echo -e "${RED}###${NC} Test connection when tunnel is running with: ${GREEN}mysql -us1**** -p -P 3307 -h 127.0.0.1${NC}"
  echo $'\r'
  echo -e "${RED}###${NC} Add real username ^^^ ${GREEN}drush @boston.test sql-connect${NC}:"

  echo $'\r'
  echo -e "${RED}###${NC} Did you remember to add the following to ${GREEN}docroot/sites/default/settings.php${NC}:"
  echo -e "${YELLOW}"
  echo "     \$databases['legacy']['default'] = array("
  echo "       'database' => 'bostondev',"
  echo "       'username' => 's1****',"
  echo "       'password' => '**************',"
  echo "       'prefix' => '',"
  echo "       'host' => '127.0.0.1',"
  echo "       'port' => '3336',"
  echo "       'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',"
  echo "       'driver' => 'mysql',"
  echo "     );"
  echo -e "${NC}"
  echo -e "${RED}###${NC} Add real username / pw ^^^ ${GREEN}drush @boston.test sql-connect${NC}:"
  echo $'\r'

fi
