<?php

/**
 * @file
 * Module file for bos_fyi.
 */

/**
 * Implements hook_theme().
 */
function bos_fyi_theme() {
  $theme['paragraph__fyi'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_fyi/templates',
  ];
  $theme['paragraph__fyi__document'] = [
    'base hook' => 'paragraph',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bos_fyi_theme_suggestions_paragraph_alter(array &$suggestions, array $variables, $hook) {
  if (isset($variables["elements"]["#paragraph"]) && $variables["elements"]["#paragraph"]->bundle() == "document") {
    $parent = $variables["elements"]["#paragraph"]->getParentEntity();
    if (isset($parent) && $parent->bundle() == "fyi") {
      $suggestions[] = "paragraph__fyi__document";
    }
  }

}
