<?php

/**
 * @file
 * Main file for the vocab_holidays module.
 */

/**
 * Implements hook_theme().
 */
function vocab_holidays_theme() {
  // $theme['taxonomy_term__311_request'] = [
  //   'base hook' => 'taxonomy_term',
  //   'path' => 'modules/custom/bos_vocab/modules/vocab_holidays/templates',
  // ];
  // $theme['field__field_external_link__311_request'] = [
  //   'base hook' => 'field',
  //   'path' => 'modules/custom/bos_vocab/modules//vocab_holidays/templates',
  // ];
  // return $theme;
}
