<?php

/**
 * @file
 * Provides an event entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function event_theme() {
  return [
    'event' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for event templates.
 *
 * Default template: event.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the event information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_event(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
