<?php

/*
  Main Drupal module for bos_search

  david 06 2024
  @file docroot/modules/custom/bos_components/modules/bos_search/bos_search.module

*/



require_once("includes/aisearch_form_theme.inc");
require_once("includes/bos_theme_theme.inc");
/**
 * Implements hook_theme().
 */
function bos_search_theme($existing, $type, $theme, $path) {

  /**
   * This defines the ai-enabled search button.
   */
  $output = [
    'aisearch_button' => [
      'template' => 'snippets/aisearch-button',
      'variables' => [
        'search_form_url' => '/search',
        'button_title' => '',
        'button_css' => '',
        'preset' => '',
      ],
    ],
  ];

  // Discover dynamic templates and themes from this module
  if (\Drupal::request()->attributes->get("_route") == "bos_search.open_AISearchForm") {
    _autodiscover_form_templates($output);
  }

  // Load component themes.
  _load_component_definitions($output);

  return $output;

}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_search_preprocess_page(&$variables) {
  /**
   * This renders the search button into the secondary_nav object.
   * TODO: need to control if/how this is enabled for a page.
   */
//  $variables['page']['content']['aisearch-button'] = [
//    '#theme' => 'aisearch-button',
//    '#search_form_url' => Url::fromRoute('bos_search.open_AISearchForm'),
//    '#button_title' => 'Search', // This has no setting in this embed style
//    '#button_css' => '',   // This has no setting in this embed style
//    '#preset' => '',  // TODO: How do we set this?
//  ];
}

function bos_search_theme_suggestions_alter(array &$suggestions, array &$variables, $hook) {
  _search_form_suggestions($suggestions, $variables, $hook);
}
