<?php

/**
 * @file
 * The Base module file for bos_tranlsate module.
 */

/**
 * Implements hook_theme().
 */
function bos_translate_theme() {
  $theme['paragraph__translate'] = [
    'base hook' => 'paragraph',
    'path' => drupal_get_path('module', 'bos_translate') . '/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_translate_preprocess_page(&$variables) {
  /*
  if (isset($variables['node']) && Drupal::currentUser()->isAnonymous()) {
    $getContentType = $variables['node']->getType();
    $contentTypes = [
      "how_to",
      "place_profile",
      "program_initiative_profile",
      "article",
      "department_profile",
    ];

    if (in_array($getContentType, $contentTypes)) :
      $variables['#attached']['library'][] = 'bos_translate/bos_translate';
    endif;
  }
  */

  $variables['#attached']['library'][] = 'bos_translate/bos_translate_js';
  $variables['#attached']['library'][] = 'bos_translate/bos_translate_css';
}
