<?php

/**
 * @file
 * Main file for the node_webform module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Markup;
use Drupal\media\Entity\Media;

/**
 * Implements hook_theme().
 *
 * Register module templates.
 */
function node_webform_theme($existing, $type, $theme, $path) {
  return [

  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_webform_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'node_webform/node_webform_css';
}
