adding:
  description: 'Consumer Key generated in the Salesforce environment.'
  key_provider: config
  key_provider_settings:
    key_value: .
    base64_encoded: false
  key_input: text_field
  key_input_settings: {  }
removing:
  description: 'Consumer Key Generated in the Salesforce environment.'
  key_provider: env
  key_provider_settings:
    env_variable: SALSEFORCE_CONSUMER_KEY
