adding:
  dependencies:
    module:
      - masquerade
  permissions:
    139: 'masquerade as content_author'
    140: 'masquerade as content_editor'
    141: 'masquerade as content_reviewer'
removing: {  }
