adding:
  dependencies:
    module:
      - masquerade
  permissions:
    - 'masquerade as administrator'
    - 'masquerade as any user'
    - 'masquerade as content_author'
    - 'masquerade as content_editor'
    - 'masquerade as content_reviewer'
    - 'masquerade as site_administrator'
    - 'masquerade as super user'
removing: {  }
