adding:
  dependencies:
    module:
      - masquerade
  permissions:
    94: 'masquerade as administrator'
    95: 'masquerade as any user'
    96: 'masquerade as content_author'
    97: 'masquerade as content_editor'
    98: 'masquerade as content_reviewer'
    99: 'masquerade as site_administrator'
    100: 'masquerade as super user'
removing: {  }
