adding:
  dependencies:
    config:
      - user.role.content_author
      - user.role.content_editor
      - user.role.content_reviewer
    module:
      - masquerade
  permissions:
    - 'masquerade as content_author'
    - 'masquerade as content_editor'
    - 'masquerade as content_reviewer'
removing: {  }
