adding:
  dependencies:
    config:
      - user.role.content_author
      - user.role.content_editor
      - user.role.content_reviewer
    module:
      - masquerade
  permissions:
    config_split_sequence_svejsv3h3k0s1pst: 'masquerade as content_author'
    config_split_sequence_nc9t64f1mcvl4661: 'masquerade as content_editor'
    config_split_sequence_c46doo65l137f8rm: 'masquerade as content_reviewer'
removing: {  }
