_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: intermediate
ignored_config_entities:
  import:
    - bos_city_score.settings
    - 'bos_commissions.settings:graphql_api_key'
    - 'bos_core.settings:ga_settings.*'
    - bos_emergency_alerts.settings
    - 'bos_geocoder.settings:google.token'
    - 'bos_google_cloud.settings:auth.service_account_*'
    - bos_mnl.settings
    - bos_theme.settings
    - geolocation_google_maps.settings
    - 'language.*|*'
    - node_elections.settings
    - node_rollcall.settings
    - slackposter.settings
  export:
    - bos_city_score.settings
    - 'bos_commissions.settings:graphql_api_key'
    - 'bos_core.settings:ga_settings.*'
    - bos_emergency_alerts.settings
    - 'bos_geocoder.settings:google.token'
    - 'bos_google_cloud.settings:auth.service_account_*'
    - bos_mnl.settings
    - bos_theme.settings
    - geolocation_google_maps.settings
    - 'language.*|*'
    - node_elections.settings
    - node_rollcall.settings
    - slackposter.settings
