toolbar_items:
  - devel.cache_clear
  - devel.configs_list
  - devel.admin_settings_link
  - devel.entity_info_page
  - devel.reinstall
  - devel.run_cron
  - devel.state_system_page
  - devel.session
