_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: maillog
  formatter: mime_mail
modules:
  bos_email:
    test:
      sender: maillog
      formatter: php_mail
