_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: 'Ping Login'
logout_menu_item_title: Logout
login_redirect_url: ''
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: true
logout_different_user: false
drupal_login_roles:
  administrator: administrator
  site_administrator: site_administrator
  developer: developer
  authenticated: '0'
  content_editor: '0'
  content_reviewer: '0'
  content_author: '0'
  metrolist_editor: '0'
  election_editor: '0'
sp_entity_id: d8local
sp_name_id_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
sp_x509_certificate: ''
sp_new_certificate: ''
sp_private_key: ''
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: 'urn:dev:sso:boston.gov'
idp_single_sign_on_service: 'https://sso-dev.boston.gov/idp/startSSO.ping?PartnerSpId=d8local'
idp_single_log_out_service: 'https://sso-dev.boston.gov/idp/startSLO.ping'
idp_change_password_service: ''
idp_certs:
  - MIIH0DCCBbigAwIBAgITFgAAOSVZeiurDpSgAwABAAA5JTANBgkqhkiG9w0BAQsFADBwMRMwEQYKCZImiZPyLGQBGRYDY29iMRYwFAYKCZImiZPyLGQBGRYGYm9zdG9uMRgwFgYKCZImiZPyLGQBGRYIY2l0eWhhbGwxJzAlBgNVBAMTHkNpdHlPZkJvc3Rvbi1FbnRlcnByaXNlLVN1Yi1DQTAeFw0yMTA1MTgxODM5MDVaFw0yNDA1MTcxODM5MDVaMGcxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJNUzEPMA0GA1UEBxMGQm9zdG9uMRUwEwYDVQQKEwxDaXR5b2ZCb3N0b24xDTALBgNVBAsTBERPSVQxFDASBgNVBAMTC3pkcGluZ2ZlZDAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiJ7vK1fiPf/fdBF370mOwy4XpgkUmHH365JmR3umsLyjT040QtL5+yyWhTXaspNsU1QhnW2nr20URN/BAVsJhARvxP0lEN9UaCXAcqSRY7HjnqHVMJAtLnAUwoTOFeiuE2Uah9Ge5QtW52ggAZcpOVBBu/E4a/vVLiJPaoS89LJBQX7bmpdOZpc+uHFv+MnGNqC8ey6dC87zKe+P4qifT8z91KwtvPKvvzL8ebemUGl8AHJFgInSsfWzadtiOnLBXdemEyt5fHJgE8QjQLg4W9o6+7zS+uLAQmnv7Cq0CVi1vXexQ+cLD399hiShd9wl3QFNjKJjuNN8rOFZ69GLMwIDAQABo4IDajCCA2YwKgYDVR0RBCMwIYIfemRwaW5nZmVkMDEuY2l0eWhhbGwuYm9zdG9uLmNvYjAdBgNVHQ4EFgQUVwAk0tZ/MiD9iEWXBCQB8EVN3ggwHwYDVR0jBBgwFoAUDIanuimnqw/y+njgpCNP4oCVxbYwggErBgNVHR8EggEiMIIBHjCCARqgggEWoIIBEoaBymxkYXA6Ly8vQ049Q2l0eU9mQm9zdG9uLUVudGVycHJpc2UtU3ViLUNBLENOPVpQQ09CU0NBQVBQMDEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9Ym9zdG9uLERDPWNvYj9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGQ2h0dHA6Ly9jcmwuYm9zdG9uLmNvYi9DZXJ0RW5yb2xsL0NpdHlPZkJvc3Rvbi1FbnRlcnByaXNlLVN1Yi1DQS5jcmwwggFHBggrBgEFBQcBAQSCATkwggE1MIG8BggrBgEFBQcwAoaBr2xkYXA6Ly8vQ049Q2l0eU9mQm9zdG9uLUVudGVycHJpc2UtU3ViLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWJvc3RvbixEQz1jb2I/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwdAYIKwYBBQUHMAKGaGh0dHA6Ly9haWEuYm9zdG9uLmNvYi9DZXJ0RW5yb2xsL1pQQ09CU0NBQVBQMDEuY2l0eWhhbGwuYm9zdG9uLmNvYl9DaXR5T2ZCb3N0b24tRW50ZXJwcmlzZS1TdWItQ0EoMSkuY3J0MA4GA1UdDwEB/wQEAwIFoDA8BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3FQiG54BehtyeT4eZmyaF9OcShcyXUF+L62mH7PtvAgFkAgENMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggIBAGE/7qQZBEMRsPy2nBZux/5zLjdUtQeZR6NRALibgNGMlxfxBXcv6rVhWEsJOnamMg7jG3WpOgkNjXnqRMIdy6ASVxc5VL5CL5s55eVl/K+o00EG6fRhzbyUjEeUC74lqrH+UE3GapQgN2lhR71qSKnlUjc0GHybJ+iMol/4e3WTWIzB1fPCgmRvOJTy/nWP/oPjl/zJPrVQ5mxXTIcAILGCDN/mSbZW2ePNF1VRgKP44j+JUnYBOedEtd60I8LxR4Oil0k90iHdPe1v5ISu+cDtLY9tyi160sUKmtVezVmFm2fiddwIxesHVSC1phvEp9xnklp4CB4X1nv8qj2i6GTf04gHe/j6TX9Ij4r/9Z1Om0ztsPYVhkdUGX75EqgPq4am9yZqCn6iMgtPQVnJLnkjC+OsWu3tU35Gna7zPitYZX0r6QVJN1b3OnDF1Ij3eE2iQk31l9+Mv8QAaU+RZ37BVnrDjM02w9vRDTfsDsUYrfQ4Q6iKidswze6jcD+BrTOATzade1ZI1dYGYqaE/5Zy5NSfMISbvRNR5jwgKGQ+tiauK6rh36c7CdZO9dHm+TKqOMz2sq9txXxnaUchAJUr2jS5g7TdgZkEdWzi7q6NI8qcZw7fl7e73/vqRKMwcZ3obEy0o2vjYRF4YitH0W31vZdgR/vh2ZwZYkU6pMb0
idp_cert_encryption: ''
unique_id_attribute: uid
map_users: false
map_users_name: true
map_users_mail: true
map_users_roles:
  administrator: administrator
  site_administrator: site_administrator
  developer: developer
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_author: content_author
  metrolist_editor: metrolist_editor
  election_editor: election_editor
create_users: true
sync_name: true
sync_mail: true
user_name_attribute: uid
user_mail_attribute: email
request_set_name_id_policy: true
strict: true
security_metadata_sign: false
security_authn_requests_sign: true
security_logout_requests_sign: true
security_logout_responses_sign: true
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: true
security_assertions_signed: false
security_assertions_encrypt: false
security_nameid_encrypted: false
security_want_name_id: true
security_request_authn_context: true
security_lowercase_url_encoding: true
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: false
debug_log_in: false
debug_log_saml_in: false
debug_log_saml_out: false
debug_phpsaml: false
use_proxy_headers: false
use_base_url: true
