_core:
  default_config_hash: zJS1GknUylh656CJSNXOupqKSqm6Xw200h1cq1eI970
enabled: true
timeout: 1800
max_timeout: 172800
padding: 20
logout_regardless_of_activity: false
no_individual_logout_threshold: false
role_logout: false
role_logout_max: false
redirect_url: /
include_destination: true
no_dialog: false
message: 'We are about to log you out for inactivity. If we do, you will lose any unsaved work. Do you need more time?'
inactivity_message: 'You have been logged out due to inactivity.'
inactivity_message_type: status
modal_width: null
enforce_admin: true
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: false
dialog_title: 'Boston.gov Alert'
disable_buttons: false
yes_button: ''
no_button: ''
whitelisted_ip_addresses: ''
