_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: php_mail
  formatter: mime_mail
modules:
  bos_email:
    none:
      sender: php_mail
      formatter: mime_mail
