project:
  docroot: ${LANDO_MOUNT}/docroot
  profile:
    name: 'bos_profile'
  themes:
    - bos_theme

# Drupal Account Credentials. These are used for installing Drupal.
drupal:
  account:
    name: admin
    password: admin
    mail: no-reply@acquia.com
  multisite:
    # Use 'default' as the name if there are no multisites.
    name: default

build:
  local:
    # Build Type = dev or prod.
    type: dev
    config:
      # Define the folder, relative to the drupal docroot, for config files to be synchronised, no trailing slash.
      # aquia requires ./config/default:
      #     @see https://docs.acquia.com/acquia-cloud/develop/config-d8/
      sync: "../config/default"
    database:
      # Set source to 'initialize' to start a fresh install.
      # Otherwise set it to 'sync' to sync from the drush-alias environment.
      source: sync
      drush-alias: "@bostond8.test"
      host: bostond8_database_1
      port: 3306

  travis:
    develop:
      # With Travis, the type will control what type of build is deployed to Acquia (dev/prod).
      type: dev
      database:
        # Set source to 'initialize' to start a fresh install.
        # Otherwise set it to sync to sync from the drush-alias environment.
        source: initialize
        drush-alias: "@bostond8.test"
      config:
        # define the folder, relative to the drupal docroot, for config files to be synchronised, no trailing slash.
        # aquia require ./config/default:
        #     @see https://docs.acquia.com/acquia-cloud/develop/config-d8/
        sync: "../config/default"
    master:
      # With Travis, the type will control what type of build is deployed to Acquia (dev/prod).
      type: prod
      database:
        # Set source to 'initialize' to start a fresh install.
        # Otherwise set it to sync to sync from the drush-alias environment.
        source: initialize
        drush-alias: "@bostond8.test"
      config:
        # define the folder, relative to the drupal docroot, for config files to be synchronised, no trailing slash.
        # aquia require ./config/default:
        #     @see https://docs.acquia.com/acquia-cloud/develop/config-d8/
        sync: "../config/default"

  terraform:
    type: prod
    database:
      # none, auto, build, sync or restore
      source: sync
      drush-alias: "@bostond8.dev"

deploy:
  # each element of the deploy object is a branch in the main CoB repo.
  develop:
    # Folder in Travis container where deploy files will be "built"
    dir: ${LANDO_MOUNT}/deploy
    # Name of the target branch in the Acquia repo.
    deploy-branch: develop-deploy
    # Path to the drush command in the Travis container.
    travis-drush-path: '${LANDO_MOUNT}/vendor/bin/drush'
    # Alias for deploy target Aquia server.
    drush-alias: "@bostond8.dev"
    # Definition of files that will and wont be copied from build to deploy.
    includes-file: ${LANDO_MOUNT}/scripts/deploy/deploy-includes.txt
    excludes-file: ${LANDO_MOUNT}/scripts/deploy/deploy-excludes.txt
    sanitize-file: ${LANDO_MOUNT}/scripts/deploy/deploy-sanitize-files.txt
    # Message we want to appear in Acquia repo for the deployment commit.
    commit-message: "Automated commit by Travis CI for Build #${travis.id}"
    # Dry-run (for testing).
    dry-run: false
    # Whether (and where) to sync the database on the deploy target. NB: copy-db=false means db left intact.
    copy-db: false
    drush-db-source: "@bostond8.stage"
    # Array of user:host for (Acquia) git remotes to be used for deployment.
    remotes:
      - bostond8@svn-29892.prod.hosting.acquia.com:bostond8.git
  master:
    # Folder in Travis container where deploy files will be "built"
    dir: ${LANDO_MOUNT}/deploy
    # Name of the target branch in the Acquia repo.
    deploy-branch: master-deploy
    # Path to the drush command in the Travis container.
    travis-drush-path: '${LANDO_MOUNT}/vendor/bin/drush'
    # Alias for deploy target Aquia server.
    drush-alias: "@bostond8.test"
    # Definition of files that will and wont be copied from build to deploy.
    includes-file: ${LANDO_MOUNT}/scripts/deploy/deploy-includes.txt
    excludes-file: ${LANDO_MOUNT}/scripts/deploy/deploy-excludes.txt
    sanitize-file: ${LANDO_MOUNT}/scripts/deploy/deploy-sanitize-files.txt
    # Message we want to appear in Acquia repo for the deployment commit.
    commit-message: "Automated commit by Travis CI for Build #${travis.id}"
    # Dry-run (for testing).
    dry-run: false
    # Whether (and where) to sync the database on the deploy target. NB: copy-db=false means db left intact.
    copy-db: false
    drush-db-source: "@bostond8.prod"
    # Array of user:host for (Acquia) git remotes to be used for deployment.
    remotes:
      - bostond8@svn-29892.prod.hosting.acquia.com:bostond8.git

# Configuration settings for new git repository.
git:
  # [Optional] Set this node (private_repo) if there is a private repo that needs to
  # be included as part of the build:
  # - It is expected that the repo is hosted on GitHub.
  # - The development machine *must* have a valid ssh key for this remote repo.
  # - The repo can contain a settings file (e.g. private.settings.php)
  # - The folder structure of the private repo must exactly match the folder structure
  #   of the main repo so that files can be copied across to the correct folders.
  private_repo:
    repo: CityOfBoston/boston.gov-d8-private.git
    branch: develop
    deploy-branch: develop
    # Where the repo will be cloned to.
    local_dir: ${LANDO_MOUNT}/setup/private
    # [optional] Provide the path to a settings script (relative to the private repo root),
    # which will be copied to the main repo and then set up to be called from (i.e. extend)
    # the sites main settings.php script.
    settings_file.rel: sites/default/settings/private.settings.php

composer:
  bin: ${LANDO_MOUNT}/vendor/bin

drush:
  bin: ${LANDO_MOUNT}/vendor/bin/drush
  cmd: ${LANDO_MOUNT}/vendor/bin/drush # -r ${LANDO_MOUNT}/docroot}# -l default
  root: ${LANDO_MOUNT}/docroot

# The testing framework is limited to the `tests` directory, and includes
# example tests and configuration for Behat, PHPUnit, and JMeter. To prevent
# this from being copied, remove the 'testing_framework' key.
testing_framework:
  reports:
    localDir: ${LANDO_MOUNT}/testing/reports
    remoteDir: testing/reports
  behat:
    javascript_driver: 'selenium2'
    # @see http://docs.behat.org/en/v2.5/guides/6.cli.html#gherkin-filters
    config: ${LANDO_MOUNT}/tests/behat/local.yml
    # An array of paths with behat tests that should be executed.
    tags: ~@hub
    # This is used for ad-hoc creation of a server via `drush rs`.
    profile: local
    # This needs to match a site entry in docroot/sites/sites.php.
    server-url: http://127.0.0.1:8888
    # If true, `drush runserver` will be used for executing tests.
    #  run-server: false
    # If true, PhantomJS GhostDriver will be launched with Behat.
    #  launch-phantom: true
  phpunit:
