<?php

/**
 * @file
 * Contains bos_metrolist.module.
 */

use Drupal\webform\Plugin\WebformHandlerInterface;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;

use Drupal\bos_metrolist\MetroListSalesForceConnection;

/**
 * Implements hook_help().
 */
function bos_metrolist_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bos_metrolist module.
    case 'help.page.bos_metrolist':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MetroList features for the City of Boston') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bos_metrolist_theme() {
  return [
    'bos_metrolist' => [
      'render element' => 'children',
    ],
    'field__boolean' => [
      'base hook' => 'field'
    ],
    'views_view_table__metrolist_ami' => [
      'base hook' => 'views'
    ],
    'views_view_metrolist_drawers' => [
      'variables' => ['view' => NULL, 'rows' => NULL],
      'path' => drupal_get_path('module', 'bos_metrolist') . '/templates',
    ],
    'paragraph__embed_view' => [
      'base hook' => 'paragraph',
    ],
    'form_element__webform_checkbox' => [
      'base hook' => 'form',
    ],
    'form_element__webform_select' => [
      'base hook' => 'form',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 *   Render variables.
 */
function bos_metrolist_preprocess_page(array &$variables) {
  if (isset($variables['node']) && !is_string($variables['node']) && $variables['node']->bundle() == 'metrolist_development') {
    $variables['#attached']['library'][] = 'bos_metrolist/metrolist_views';
    $variables['attributes']['class'][] = 'mn';
  }

  // @TODO: Find a better way to attach this class to the Webform MetroList Listing Page
  if (isset($variables["page"]["#title"]) && $variables["page"]["#title"] == "MetroList Listing") {
    $variables['attributes']['class'][] = 'mn';
  }

  // @TODO: attaching CSS to override the grid-of-cards, should move that CSS to separate file and lib for better reuse
  if (isset($variables['node']) && !is_string($variables['node']) && $variables["node"]->url() == '/metrolist') {
    $variables['#attached']['library'][] = 'bos_metrolist/metrolist_views';
  }

}

/**
 * Implements hook_block_build_alter().
 */
function bos_metrolist_form_taxonomy_term_ml_income_eligibility_ami_thold_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $incomeFields = [
    'field_total_house_income_data',
    'total_house_income_data_bpda',
    'total_house_income_data_hud'
  ];

  foreach ($incomeFields as $incomeField) {
    if (isset($form[$incomeField])) {
      foreach (Element::children($form[$incomeField]['widget']) as $key => $field) {
        $person_number = ($key + 1);
        $person_label = ngettext(' person', ' people', $person_number);
        $form[$incomeField]['widget'][$key]['value']['#field_suffix'] = " for <b>$person_number</b> $person_label / year";
      }
    }
  }

}

/**
 * Implements hook_preprocess_hook()
 */
function bos_metrolist_preprocess_views_view_metrolist_drawers(&$variables) {
  template_preprocess_views_view_unformatted($variables);

  $view = $variables['view'];
  $rows = $variables['rows'];

  $options = $view->style_plugin->options;

  $variables['show_all_units_button'] = $options['show_all_units_button'];
  $variables['show_all_units_button_text'] = $options['show_all_units_button_text'];
  $variables['hide_all_units_button_text'] = $options['hide_all_units_button_text'];

  // Set the bounds via Query params.
  // 1+2+3.
  $bounds['beds'] = $view->getRequest()->get('bedrooms') ?? NULL;
  // 30-120
  $bounds['ami'] = $view->getRequest()->get('ami') ?? NULL;
  // Rent / own.
  $bounds['type'] = $view->getRequest()->get('type') ?? NULL;

  // Sort by type first if it is set so that we can populate the header and footer data correctly.
  if (is_null($bounds['type']) || $bounds['type'] == 'rent') {
    $variables['view']->sort['field_ml_unit_occupancy_type_target_id']->options['order'] = 'ASC';
  }
  else {
    $variables['view']->sort['field_ml_unit_occupancy_type_target_id']->options['order'] = 'DESC';
    $variables['view']->result = array_reverse($variables['view']->result);
  }

  foreach ($rows as $row) {
    bos_metrolist_set_views_active_rows($rows, $bounds, $row);
  }

  $variables['email_button'] = $options['show_email_button'] ? bos_metrolist_build_email_button($variables) : NULL;
  $variables['print_button'] = $options['show_print_button'] ? bos_metrolist_build_print_button($variables) : NULL;

  // @TODO: Change out to a config.
  $options['show_share_buttons'] = TRUE;
  $variables['share_button_facebook'] = $options['show_share_buttons'] ? bos_metrolist_build_share_button($variables, 'facebook') : NULL;
  $variables['share_button_twitter'] = $options['show_share_buttons'] ? bos_metrolist_build_share_button($variables, 'twitter') : NULL;
  // $variables['share_button_instagram'] = $options['show_share_buttons'] ? bos_metrolist_build_share_button($variables, 'instagram') : NULL;

  $variables['report_unavailable_button'] = bos_metrolist_build_unavailable_button($variables);

}

/**
 * Implements hook_views_pre_build()
 */
function bos_metrolist_views_pre_build(ViewExecutable $view) {
  if ($view->current_display == 'block_metrolist_development_units' && $view->filter) {

    $type = $view->getRequest()->get('type') ?? NULL;
    $assignments = $view->getRequest()->get('assignment') ?? NULL;

    if ($type == 'rent') {
      $view->filter['field_ml_unit_occupancy_type_target_id']->value = [33296];
    }
    elseif ($type == 'sale' || $type == 'own') {
      $view->filter['field_ml_unit_occupancy_type_target_id']->value = [33356];
    }

    if ($assignments == 'first') {
      $view->filter['field_ml_unit_user_guide_type_target_id']->value = [33326];
    }
    elseif ($assignments == 'lottery') {
      $view->filter['field_ml_unit_user_guide_type_target_id']->value = [33306];
    }
    elseif ($assignments == 'waitlist') {
      $view->filter['field_ml_unit_user_guide_type_target_id']->value = [33346];
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array $rows
 *   Referenced set of Rows.
 * @param array $bounds
 *   The bounds from the filter params.
 * @param array $row
 *   Current row.
 */
function bos_metrolist_set_views_active_rows(array &$rows, array $bounds = [], array $row = []) {
  $rowResult = $row['content']['#row'] ?? NULL;
  $index = $rowResult->index ?? NULL;

  // Let value of 'sale' map to 'own' for the JsApp filter values.
  $type = (strtolower($bounds['type']) == 'sale') ? 'own' : strtolower($bounds['type']);
  $type = strtolower($rowResult->_relationship_entities["field_ml_unit_occupancy_type"]->label()) == $type ? TRUE : FALSE;

  $amiValue = preg_replace('/\D/', '', $rowResult->_relationship_entities["field_ml_incm_elgblty_ami_thold"]->label());
  $amiBounds = explode('-', $bounds['ami']);
  // Sort the ami bounds in case we are given them in the wrong order in the url filters.
  sort($amiBounds);
  $amiLow = $amiBounds[0] ?? NULL;
  $amiHigh = $amiBounds[1] ?? NULL;

  $ami = ($amiValue >= $amiLow && $amiValue <= $amiHigh) ? TRUE : FALSE;

  $bedsBounds = explode(' ', $bounds['beds']);
  $beds = in_array($rowResult->node__field_ml_unit_num_of_bedrooms_field_ml_unit_num_of_bed, $bedsBounds);

  if (!is_null($bounds['beds']) && !$beds) {
    // $rows[$index] = $row;
    return;
  }
  elseif (!is_null($bounds['ami']) && !$ami) {
    // $rows[$index] = $row;
    return;
  }
  elseif (!is_null($bounds['type']) && !$type) {
    // $rows['outOfBounds'][$index] = $row;
    return;
  }
  else {
    // Set a class to bold the drawer title.
    $rows[$index]['attributes']->addClass('active');
    // $rows[$index] = $row;
    return;
  }

}

/**
 * Build the email button.
 */
function bos_metrolist_build_email_button($variables) {
  $nid = $variables['view']->argument['nid']->value[0] ?? NULL;
  $development = $variables["view"]->result[0]->_relationship_entities["field_ml_development"] ?? NULL;

  $developmentTitle = $development->label();
  $developmentURL = $development->toUrl()->setOption('absolute', TRUE)->toString();

  $button = [];

  $title = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    // '#value' => $variables['view']->style_plugin->options['email_button_text'],
    '#value' => '',
    '#attributes' => [
      'style' => ['display: block;', 'flex:2;', 'white-space: nowrap;'],
      'class' => ['']
    ],
  ];

  $icon = [
    '#type' => 'html_tag',
    '#tag' => 'img',
    '#attributes' => [
      'src' => 'https://assets.boston.gov/icons/experiential_icons/email.svg',
      'style' => [
        'max-height: 42px;',
        'margin: 0;',
        'padding: 0;',
        'display: block;',
        'flex:1'
      ],
      'class' => ['']
    ],
    'title' => $title,
  ];

  $button['#title'] = render($icon);

  $button['#type'] = 'link';

  $button['#attributes'] = [
    'class' => [
      'ml-action-btn',
      'hide-form'
    ],
    'title' => 'Email',
    // 'style' => ['width: 10rem;', 'display: flex;', 'align-items: center;', 'padding: 0;'],
  ];

  $button['#url'] = Url::fromUri('mailto:')
    ->setOption('query', [
      'subject' => "Share Metrolist Listing - $developmentTitle",
      'body' => "Share Metrolist Listing - $developmentTitle ( $developmentURL )",
    ]);

  // Use to link to a webform
  // $button['#url'] = \Drupal\Core\Url::fromRoute('entity.webform.canonical')
  // ->setRouteParameter('webform', 'share_metrolist_listing')
  // ->setRouteParameter('source_entity_type', 'node')
  // ->setRouteParameter('source_entity_id', $nid);.

  return $button;
}

/**
 * Build print button.
 */
function bos_metrolist_build_print_button($variables) {
  $button = [];

  $title = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    // '#value' => $variables['view']->style_plugin->options['print_button_text'],
    '#value' => '',
    '#attributes' => [
      'style' => ['display: block;', 'flex:2;', 'white-space: nowrap;'],
      'class' => ['']
    ],
  ];

  $icon = [
    '#type' => 'html_tag',
    '#tag' => 'img',
    '#attributes' => [
      'src' => 'https://assets.boston.gov/icons/experiential_icons/printer.svg',
      'style' => [
        'max-height: 42px;',
        'margin: 0;',
        'padding: 0;',
        'display: block;',
        'flex:1'
      ],
      'class' => ['']
    ],
    'title' => $title,
  ];

  $button['#title'] = render($icon);

  $button['#type'] = 'link';

  $button['#attributes'] = [
    'class' => [
      'ml-action-btn',
      'hide-form'
    ],
    'title' => 'Print',
    // 'style' => ['width: 10rem;', 'display: flex;', 'align-items: center;', 'padding: 0;'],
    'onclick' => 'window.print()',
  ];

  $button['#url'] = Url::fromUri('internal:#print');

  return $button;
}

/**
 * Build share buttons.
 *
 * @param array $variables
 *   Vars.
 * @param string $provider
 *   Social provider (facebook, twitter)
 *
 * @return array
 *   Button render array
 */
function bos_metrolist_build_share_button(array $variables, $provider = '') {

  // @todo: Change out to a yml config or field configs
  $socials = [
    'facebook' => [
      'label' => 'Facebook',
      'icon' => 'https://patterns.boston.gov/images/global/icons/social-media/icon-facebook.svg',
      'url' => 'https://www.facebook.com/sharer/sharer.php',
    ],
    'twitter' => [
      'label' => 'Twitter',
      'icon' => 'https://patterns.boston.gov/images/global/icons/social-media/icon-twitter.svg',
      'url' => 'https://twitter.com/intent/tweet',
      'hashtags' => 'bosmetrolist,BosAH',
    ],
    'instagram' => [
      'label' => 'Instagram',
      'icon' => 'https://patterns.boston.gov/images/global/icons/social-media/icon-instagram.svg',
      'url' => 'https://instagram.com',
    ],
  ];

  $nid = $variables['view']->argument['nid']->value[0] ?? NULL;
  $development = $variables["view"]->result[0]->_relationship_entities["field_ml_development"] ?? NULL;

  $developmentTitle = $development->label();
  $developmentURL = $development->toUrl()->setOption('absolute', TRUE)->toString();

  $button = [];

  $title = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    // '#value' => $variables['view']->style_plugin->options['email_button_text'],
    // '#value' => $socials[$provider]['label'],
    '#value' => '',
    '#attributes' => [
      'style' => ['display: block;', 'flex:2;', 'white-space: nowrap;'],
      'class' => ['']
    ],
  ];

  $icon = [
    '#type' => 'html_tag',
    '#tag' => 'img',
    '#attributes' => [
      'src' => $socials[$provider]['icon'],
      'style' => [
        'max-height: 36px;',
        'margin: 0;',
        'padding: 0;',
        'display: block;',
        'flex:1;',
        'background-color: #fff;',
        'border-radius: 50%;',
        'border: 1px solid #fff;',
      ],
      'class' => ['']
    ],
    'title' => $title,
  ];

  $button['#title'] = render($icon);

  $button['#type'] = 'link';

  $button['#attributes'] = [
    'class' => [
      'ml-action-btn',
      'hide-form'
    ],
    'target' => '_blank',
    'title' => $socials[$provider]['label'],
    // 'style' => ['width: 10rem;', 'display: flex;', 'align-items: center;', 'padding: 0;'],
  ];

  $button['#url'] = Url::fromUri($socials[$provider]['url']);

  if ($provider == 'facebook') {
    $button['#url']->setOption('query', [
      'u' => $developmentURL,
    ]);
  }

  if ($provider == 'twitter') {
    $button['#url']->setOption('query', [
      // 'subject' => "Share Metrolist Listing - $developmentTitle",
      // 'body' => "Share Metrolist Listing - $developmentTitle ( $developmentURL )",
      // 'url' => \Drupal::token()->replace("[current-page:url]", ['node' => $development], ['clear' => TRUE]),
      'url' => $developmentURL,
      // 'text' => \Drupal::token()->replace("New listing on Boston Metrolist: [current-page:title]", ['node' => $development], ['clear' => TRUE]),
      'text' => "New listing on Boston Metrolist: $developmentTitle",
      'hashtags' => $socials[$provider]['hashtags'],
    ]);
  }

  // Use to link to a webform
  // $button['#url'] = \Drupal\Core\Url::fromRoute('entity.webform.canonical')
  // ->setRouteParameter('webform', 'ml_listing_unavailable_form')
  // ->setRouteParameter('source_entity_type', 'node')
  // ->setRouteParameter('source_entity_id', $nid);.

  return $button;
}

/**
 * Build unavailable button.
 *
 * @param array $variables
 *   Variables.
 *
 * @return array
 *   Button render array
 */
function bos_metrolist_build_unavailable_button(array $variables) {

  $nid = $variables['view']->argument['nid']->value[0] ?? NULL;
  $development = $variables["view"]->result[0]->_relationship_entities["field_ml_development"] ?? NULL;

  $developmentTitle = $development->label();
  $developmentURL = $development->toUrl()->setOption('absolute', TRUE)->toString();

  $button = [];

  $title = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    '#value' => t("Report Unit as Unavailable"),
    '#attributes' => [
      'style' => ['display: block;', 'flex:2;', 'white-space: nowrap;'],
      'class' => ['']
    ],
  ];

  $icon = [
    '#type' => 'html_tag',
    '#tag' => 'img',
    '#attributes' => [
      'src' => 'https://patterns.boston.gov/images/global/icons/experiential/important.svg',
      'style' => [
        'max-height: 36px;',
        'margin: 0;',
        'padding: 0;',
        'display: block;',
        'flex:1;',
        'background-color: #fff;',
        'border-radius: 50%;',
        'border: 1px solid #fff;',
      ],
      'class' => ['']
    ],
    'title' => $title,
  ];

  $button['#title'] = render($icon);

  $button['#type'] = 'link';

  $button['#attributes'] = [
    'class' => [
      'webform-dialog',
      'webform-dialog-narrow',
      // 'btn btn--sm',
      // 'm-r100',
      'ml-action-btn',
      'hide-form'
    ],
    'title' => t("Report Home Unavailable"),
    // 'style' => ['width: 10rem;', 'display: flex;', 'align-items: center;', 'padding: 0;'],
  ];

  // Use to link to a webform.
  $button['#url'] = Url::fromRoute('entity.webform.canonical')
    ->setRouteParameter('webform', 'ml_listing_unavailable_form')
    ->setRouteParameter('source_entity_type', 'node')
    ->setRouteParameter('source_entity_id', $nid);

  return $button;
}

/**
 * Split all rows into two groups.
 */
function bos_metrolist_set_views_row_group(&$rowGroups = [], $bounds = [], $row = []) {
  $rowResult = $row['content']['#row'] ?? NULL;
  $index = $rowResult->index ?? NULL;

  // Let value of 'sale' map to 'own' for the JsApp filter values.
  $type = (strtolower($bounds['type']) == 'sale') ? 'own' : strtolower($bounds['type']);
  $type = strtolower($rowResult->_relationship_entities["field_ml_unit_occupancy_type"]->label()) == $type ? TRUE : FALSE;

  $amiValue = preg_replace('/\D/', '', $rowResult->_relationship_entities["field_ml_incm_elgblty_ami_thold"]->label());
  $amiBounds = explode('-', $bounds['ami']);
  // Sort the ami bounds in case we are given them in the wrong order in the url filters.
  sort($amiBounds);
  $amiLow = $amiBounds[0] ?? NULL;
  $amiHigh = $amiBounds[1] ?? NULL;

  $ami = ($amiValue >= $amiLow && $amiValue <= $amiHigh) ? TRUE : FALSE;

  $bedsBounds = explode(' ', $bounds['beds']);
  $beds = in_array($rowResult->node__field_ml_unit_num_of_bedrooms_field_ml_unit_num_of_bed, $bedsBounds);

  if (!is_null($bounds['beds']) && !$beds) {
    $rowGroups['outOfBounds'][$index] = $row;
    return;
  }
  elseif (!is_null($bounds['ami']) && !$ami) {
    $rowGroups['outOfBounds'][$index] = $row;
    return;
  }
  elseif (!is_null($bounds['type']) && !$type) {
    $rowGroups['outOfBounds'][$index] = $row;
    return;
  }
  else {
    $rowGroups['inBounds'][$index] = $row;
    return;
  }

}

/**
 * Create a new Metrolist Listing form after requested via the email form.
 */
function bos_metrolist_create_listing_submission($email = 'John.Smith@example.com') {

  $webform_id = 'metrolist_listing';
  $webform = Webform::load($webform_id);
  // Create webform submission.
  $values = [
    'webform_id' => $webform->id(),
    // @TODO: not sure we need this... need to test
    'in_draft' => TRUE,
    'data' => [
      'contact_email' => $email,
    ],
  ];

  /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
  $webform_submission = WebformSubmission::create($values);
  $webform_submission->save();
  $webform_submission->getTokenUrl('update');
  return $webform_submission;
}

/**
 * Implements hook_webform_handler_invoke_alter().
 */
function bos_metrolist_webform_handler_invoke_alter(WebformHandlerInterface $handler, $method_name, array &$args) {
  if ($method_name == 'pre_save') {
    $test = 2;
    // $args[1]->data["hidden_subject"] = $args[1]->data["hidden_subject"] . "-ALTERD";
  }
}

/**
 * Implements hook_form_alter().
 */
function bos_metrolist_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $test = $form_state->getValues();
}

/**
 * Used to inject to Listing form token into the email from the email entry form.
 */
function bos_metrolist_webform_submission_presave(WebformSubmission $webform_submission) {
  if ($webform_submission->getWebform()->id() == 'metrolist_listing_entry_form') {
    $email = $webform_submission->getElementData('email');
    $token = bos_metrolist_create_listing_submission($email)->getToken();
    $message = str_replace('#metrolist:new-listing:token#', $token, $webform_submission->getElementData('hidden_message'));
    $webform_submission->setElementData('hidden_message', $message);
  }
}

/**
 * Implements hook_webform_element_alter().
 *
 * @param array $element
 *   Webform element / field.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Active Webform form_state.
 * @param array $context
 *   Context data about the webform.
 */
function bos_metrolist_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--select_contact') {
    $salesForce = new MetroListSalesForceConnection();
    $webformSID = $element['#webform_submission'] ?? NULL;

    $salesForce->loadWebformSubmission($webformSID);
    $contactOptions = $salesForce->getContactOptionsByEmail($salesForce->getContactEmail());

    if ($contactOptions) {
      $element['#options'] = array_merge($element['#options'], $contactOptions);
    }

  }

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--select_development') {
    $salesForce = new MetroListSalesForceConnection();
    $webformSID = $element['#webform_submission'] ?? NULL;
    $salesForce->loadWebformSubmission($webformSID);
    $contactSID = $salesForce->webformSubmission() ? $salesForce->webformSubmission()->getElementData('select_contact') : NULL;

    $developmentOptions = $salesForce->getDevelopmentOptionsByContactSid($contactSID);

    if ($developmentOptions) {
      $element['#options'] = array_merge($element['#options'], $developmentOptions);
    }

  }

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--units') {
    $salesForce = new MetroListSalesForceConnection();
    $excludeOptions = ['Homeless Set Aside'];
    $amiOptions = $salesForce->getPickListValues('Development_unit__C', 'Income_Eligibility_AMI_Threshold__c', $excludeOptions) ?? NULL;

    if ($amiOptions) {
      $element['#element']['ami']['#options'] = $amiOptions;
    }
  }

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--region') {
    $salesForce = new MetroListSalesForceConnection();
    $regionOptions = $salesForce->getPickListValues('Development__C', 'Region__c') ?? NULL;

    if ($regionOptions) {
      $element['#options'] = $regionOptions;
    }
  }

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--city') {
    $salesForce = new MetroListSalesForceConnection();
    $cityOptions = $salesForce->getPickListValues('Development__C', 'City__c') ?? NULL;

    if ($cityOptions) {
      $element['#options'] = $cityOptions;
    }
  }

  if (isset($element['#webform_id']) && $element['#webform_id'] == 'metrolist_listing--neighborhood') {
    $salesForce = new MetroListSalesForceConnection();
    $attachments = $salesForce->getAttachmentsBySid('a2lV0000001eRfs');

    $test = $salesForce->client()->apiCall("sobjects/Attachment/00PV0000006bjExMAI/Body");
//    $test = $salesForce->client()->httpRequestRaw("https://boston-dnd--fullcopy.my.salesforce.com/services/data/v44.0/sobjects/Attachment/00PV0000006bjExMAI/Body");


    $neighborhoodOptions = $salesForce->getPickListValues('Development__C', 'Neighborhood__c') ?? NULL;

    if ($neighborhoodOptions) {
      $element['#options'] = $neighborhoodOptions;
    }
  }

}
