<?php

/**
 * @file
 * The Base module file for bos_news_announcements module.
 */

use Drupal\bos_core\BackgroundResponsiveImage;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function bos_news_and_announcements_theme() {
  $theme['paragraph__news_and_announcements'] = [
    'base hook' => 'paragraph',
    'path' => drupal_get_path('module', 'bos_news_and_announcements') . '/templates',
  ];
  $theme['views_view_unformatted__news_and_announcements'] = [
    'base hook' => 'view',
    'path' => drupal_get_path('module', 'bos_news_and_announcements') . '/templates',
  ];
  $theme['views_view_fields__news_and_announcements'] = [
    'base hook' => 'view',
    'path' => drupal_get_path('module', 'bos_news_and_announcements') . '/templates',
  ];
  $theme['viewfield__paragraph__news_and_announcements'] = [
    'base hook' => 'viewfield',
    'path' => drupal_get_path('module', 'bos_news_and_announcements') . '/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_views_view_fields().
 */
function bos_news_and_announcements_preprocess_views_view_fields__news_and_announcements(&$variables) {

  $photo_id = Html::getUniqueId('cd-ic-' . $variables["row"]->nid);
  $variables['photo_id'] = $photo_id;

  $thumb_url = $variables["fields"]["field_thumbnail"]->content;

  if (isset($thumb_url)) {
    $nestedDivs = [
      ["div" => "b"],
      ["div" => "cd-ic " . $variables['photo_id']],
    ];
    $background_image = str_replace("\n", "", strip_tags(trim($thumb_url)));
    $background_image = preg_replace("~.*/sites/default/files~", "public:/", $background_image);
  }
  else {
    $nestedDivs = [
      ["div" => "b"],
      ["div" => "cd-ic hro--d " . $variables['photo_id']],
    ];
    $mode = _bos_theme_library();
    $lib = \Drupal::service('library.discovery')
      ->getLibraryByName('bos_theme', 'global-styling.' . $mode);
    $background_image = $lib['remote'] . "/images/public/icons/news.svg";
  }

  // Create the anchor.
  $variables["content"]["thumbnail"] = BackgroundResponsiveImage::createBackgroundFramework($nestedDivs);

  // Create and insert the media queries.
  $css = BackgroundResponsiveImage::buildMediaQueries($background_image, "card_images_2w",".$photo_id");
  $variables['#attached']['html_head'][] = [
    [
      "#tag" => "style",
      "#value" => $css,
      "#weight" => 100,
    ],
    'post-intro-image-css-' . $photo_id,
  ];
}
