<?php

/**
 * @file
 * Module file for bos_assessing.
 */

use Drupal\Core\Render\Markup;
use Drupal\Core\Config;

/**
 * Implements hook_theme().
 */
function bos_assessing_theme() {
  $theme['bos_assessing'] = [
    'template' => 'bos-assessing',
    'variables' => [
    	'data_full' => NULL,
      'data_res' => NULL,
      'data_condo' => NULL,
      'data_value_history' => NULL,
      'data_owner' => NULL,
      'data_owners_current' => NULL,
      'data_coords' => NULL,
      'data_year_current' => NULL,
      'data_year_fiscal' => NULL,
    ]
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_assessing_preprocess_page(&$variables) {
  $pathinfo = Drupal::request()->getPathInfo();
  $pathinfo = explode("/", $pathinfo);
  if (end($pathinfo) != "edit" && end($pathinfo) != "revisions" && strpos($pathinfo[1], 'assessing-online') !== false) {
     _bos_content_fix_attributes($variables);
    // Make responsive to menu appearing on right by adding class mn.
    $variables["attributes"]->addClass("mn");
    $variables["attributes"]->addClass("page");
  }
}

function bos_assessing_library_info_build() {
  $libraries = [];
  $modName = basename(__FILE__, ".module");
  $modulePath = drupal_get_path("module", $modName);
  $api_key = \Drupal::config('geolocation_google_maps.settings')->get("google_map_api_key");
  $js_path = "https://maps.googleapis.com/maps/api/js?key=$api_key&libraries=drawing";
  $libraries['assessing_map'] = [
    'version' => '1.x',
    'js' => [
      $js_path => ['type' => 'external', 'minified' => TRUE],
      '/modules/custom/bos_components/modules/bos_assessing/js/assessing_map.js' => ['type' => 'external', 'minified' => TRUE],
    ],
    'css' => [
      'layout' => [
          '/modules/custom/bos_components/modules/bos_assessing/css/assessing.css' => [],
        ],
    ],
  ];

  return $libraries;
}
