<?php

/**
 * @file
 * Provides a place profile entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function node_place_profile_theme() {
  return [
    'node__place_profile' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_place_profile_preprocess_node__place_profile(&$variables) {
  _bos_content_fix_attributes($variables);
  $variables['attributes']->addClass("desktop-100");
  $variables['attributes']->addClass("clearfix");
  $variables['attributes']->setAttribute("id", "node-" . $variables['elements']['#node']->id());

  $variables['attributes']->addClass("with-hero");

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_place_profile_preprocess_page(&$variables) {
  if (isset($variables["node"]) && $variables["node"]->bundle() == "place_profile") {
    $variables['header_image'] = TRUE;
  }
}

/**
 * Prepares variables for place profile templates.
 *
 * Default template: place-profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the place profile information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_node__place_profile(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
