<?php

/**
 * @file
 * Provides a program initiative profile entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function node_program_initiative_profile_theme() {
  return [
    'node__program_initiative_profile' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_event_preprocess_node__program_initiative_profile(&$variables) {
  _bos_theme_fix_attributes($variables);
  $variables['attributes']->addClass('relative-free-article');
  $variables['attributes']->addClass('clearfix');
  $variables['attributes']->setAttribute('id', 'node-' . $variables['elements']['#node']->id());
}

/**
 * Prepares variables for program initiative profile templates.
 *
 * Default template: program-initiative-profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the program initiative profile
 *     information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_node_program_initiative_profile(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
