<?php

/**
 * @file
 * Provides an emergency alert entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function emergency_alert_theme() {
  return [
    'emergency_alert' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for emergency alert templates.
 *
 * Default template: emergency-alert.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the emergency alert information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_emergency_alert(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
