rest_api_version:
  label: ''
  url: ''
  version: '39.0'
use_latest: true
global_push_limit: 100000
pull_max_queue_size: 100000
show_all_objects: false
standalone: false
limit_mapped_object_revisions: 10
_core:
  default_config_hash: 52LglOGViK4vfNygfZbuM0OeLXOkRDd70jxnLOX4KOc
