metrolist_affordable_housing.metrolist_affordable_housing_type.*:
  type: config_entity
  label: 'Metrolist Affordable Housing type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
