<?php

/**
 * @file
 * The Base module file for bos_external_link module.
 */

/**
 * Implements hook_theme().
 */
function bos_city_score_theme() {
  return [
    'paragraph__city_score_dashboard' => [
      'base hook' => 'paragraph',
      'path' => 'modules/custom/bos_components/modules/bos_city_score/templates',
      'template' => 'paragraph--city-score-dashboard',
      ],
    ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_city_score_preprocess_paragraph(&$variables) {
  // Add the js and css for the city-score component.
  if ($variables['elements']['#paragraph']->bundle() == "city_score_dashboard") {
    $variables['#attached']['library'][] = "bos_city_score/heroku.style";
  }
}
