<?php

/**
 * @file
 * Provides a metrolist affordable housing entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function node_metrolist_theme() {
  return [
    'metrolist_affordable_housing' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for metrolist affordable housing templates.
 *
 * Default template: metrolist-affordable-housing.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the metrolist affordable housing information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_node_metrolist(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
