<?php

/**
 * @file
 * Provides a how-to entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function how_to_theme() {
  return [
    'how_to' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for how-to templates.
 *
 * Default template: how-to.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the how-to information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_how_to(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
