username: 'Drupal {{branch}} Publish'
icon_url: https://boston.gov/digitalteamicon.png

pretext: Publish of <{{repositoryUrl}}|{{repositoryName}}> reports {{jobStatus}}.
title: <{{workflowRunUrl}}|Publish {{#if jobStatus='Success'}}Completed{{else}}INCOMPLETED{{/if}}>
title_link: {{workflowRunUrl}}

text: |

fallback: |-
  [GitHub] {{payload.repository.name}} finished

fields:
  - title: Job Steps
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: false

footer: >-
  {{payload.enterprise.name}}, <{{payload.repository.homepage}}|{{payload.repository.name}}>: _GitHub Action:publish.yml_#{{runNumber}}

colors:
  info: '#5DADE2'
  success: '#0d5c1f'
  failure: '#821414'
  cancelled: '#7D3C98'
  default: '#5DADE2'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
