username: 'Drupal {{branch}} Deploy'
icon_url: https://boston.gov/digitalteamicon.png

pretext: A {{branch}} deployment of <{{repositoryUrl}}|{{repositoryName}}> has been initiated.
title: <{{workflowRunUrl}}|Build Start>
title_link: {{workflowRunUrl}}

text: |
  A {{eventName}} to {{branch}} has started a build and deploy pipeline.

