username: 'Acquia Environment Deploy'
icon_url: https://boston.gov/digitalteamicon.png

pretext: A deployment to Acquia of the branch {{branch}} from the repository <{{repositoryUrl}}|{{repositoryName}}> has been initiated.
title: <{{workflowRunUrl}}|Deploy Start>
title_link: {{workflowRunUrl}}

text: |
  A GitHub Action has been executed because a {{eventName}} event on the branch {{branch}}. This has started a deploy process for this branch.

