<?php

/**
 * @file
 * Main file for the bos_content module.
 */

/**
 * Ensures the attributes element of a preprocess_hook is an attributes object.
 *
 * @param array $variables
 *   The variables object from a preprocess hook.
 * @param string $check_field
 *   The attribute field.
 */
function _bos_content_fix_attributes(array &$variables, string $check_field = "attributes") {
  if (function_exists("_bos_core_fix_attributes")) {
    _bos_core_fix_attributes($variables, $check_field);
  }
}
