<?php

/**
 * @file
 * Provides a person profile entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function person_profile_theme() {
  return [
    'person_profile' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for person profile templates.
 *
 * Default template: person-profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the person profile information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_person_profile(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
