<?php

/**
 * @file
 * Provides an node_event entity type.
 */

use Drupal\Core\Render\Markup;
use Drupal\Core\Render\Element;
use Drupal\bos_core\BackgroundResponsiveImage;

/**
 * Implements hook_theme().
 */
function node_event_theme() {
  return [
    'event' => [
      'render element' => 'elements',
    ],
    'node__event' => [
      'render element' => 'elements',
      'base_hook' => 'node',
    ],
    'field__node__field_event_type__event' => [
      'base_hook' => 'field',
    ],
    'detail_item' => [
      'template' => 'snippets/detail-item',
      'variables' => [
        "label" => NULL,
        "body" => NULL,
        "image" => NULL,
        "classes" => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for event templates.
 *
 * Default template: event.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the event information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_node__event(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  // Handle intro_image if present.
  // Has to happen in this template_preprocess_hook or does not #attach(ed).
  if (isset($variables['content']['field_intro_image'])) {
    $background_image = $variables["elements"]["field_intro_image"];
    switch ($variables["elements"]["#view_mode"]) {
      case "featured_item":
        break;

      default:
        if (isset($background_image["#items"]) && $background_image["#items"]->count()) {
          $photo_id = Html::getUniqueId('hro');
          $variables['paragraph']->_photo_id = $photo_id;
          $variables['photo_id'] = $photo_id;
          $css = BackgroundResponsiveImage::createBackgroundCss($background_image, ".$photo_id");
          $variables['#attached']['html_head'][] = [
            [
              "#tag" => "style",
              "#value" => $css,
              "#weight" => 100,
            ],
            'event-intro-image-css',
          ];
        }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_event_preprocess_page(&$variables) {
  if (!isset($variables["node"]) || (isset($variables["node"]) && is_object($variables['node']) && $variables["node"]->bundle() != "event")) {
    return;
  }

  // Now make and render the Intro_image block.
  $variables['header_image'] = FALSE;
  if (isset($variables['content']['field_intro_image']) && $variables["node"]->get('field_intro_image')->count()) {
    $variables['header_image'] = TRUE;
    _bos_content_fix_attributes($variables);
    $variables["attributes"]->addClass("mn");
    $variables["attributes"]->setAttribute("id", "page");
    $nestedElement = [
      ["div" => "b b--fw b--fw--480"],
      ["div" => $variables['photo_id'] . " hro hro--pt hro--pb"],
    ];
    $variables["content"]["intro_image"] = BackgroundResponsiveImage::createBackgroundFramework($nestedElement);
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_event_preprocess_node__event(&$variables) {
  _bos_theme_fix_attributes($variables);
  $variables['attributes']->addClass('desktop-100');

  $vars = [
    'classes' => [
      'icon' => 'icon-time',
      'label' => 'detail-item--secondary',
      'body' => 'detail-item__body--tertiary',
      'detail' => 'detail-item--middle',
    ],
  ];
  // Render the time element of the event date into a detail_item.
  if (isset($variables["content"]["field_date_range"]["#object"])) {
    // TODO: test when multiple dates. (in twig node-event.html.twig)
    $event_date = $variables['elements']['#node']->field_date_range[0]->value;
    // All dates stored in UTC in DB.
    $event_date = strtotime($event_date . " +0000");
    $vars["label"] = \Drupal::service('date.formatter')->format($event_date, "date_format_calendar_time", "", drupal_get_user_timezone());

    if (!empty($variables['elements']['#node']->field_date_range[0]->end_value)) {
      $event_end_date = $variables['elements']['#node']->field_date_range[0]->end_value;
      $event_end_date = strtotime($event_end_date . " +0000");
      $vars["label"] .= " - " . \Drupal::service('date.formatter')
        ->format($event_end_date, "date_format_calendar_time", "", drupal_get_user_timezone());
    }
    $variables["content"]["field_event_times"] = Drupal::theme()->render("detail_item", $vars);
  }

  $vars = [
    'classes' => [
      'label' => 'detail-item--left',
      'body' => 'detail-item--secondary',
      'detail' => 'detail-item--secondary',
    ],
  ];

  // Render the cost into a details_item.
  if (isset($variables["content"]["field_cost"]["#title"])) {
    $vars["label"] = $variables["content"]["field_cost"]["#title"] . ":";
    $vars["body"] = $variables["content"]["field_cost"];
    $variables["content"]["cost"] = Drupal::theme()->render("detail_item", $vars);
  }
  else {
    $vars["label"] = "Price:";
    $vars["body"] = Markup::create('<div class="detail-item__body detail-item__body--secondary field-item">FREE</div>');
    $variables["content"]["cost"] = Drupal::theme()->render("detail_item", $vars);
  }

  // Render the event_contact into a details_item.
  if (isset($variables["content"]["field_event_contact"]["#title"])) {
    $vars["label"] = $variables["content"]["field_event_contact"]["#title"] . ":";
    $vars["body"] = $variables["content"]["field_event_contact"];
    $variables["content"]["field_event_contact"] = Drupal::theme()
      ->render("detail_item", $vars);
  }
  else {
    unset($variables["content"]["field_event_contact"]);
  }

  if (!isset($variables["content"]["field_event_type"]["#title"])) {
    unset($variables["content"]["field_event_type"]);
  }

  // Render the published_date into a details_item.
  if (isset($variables["content"]["field_published_date"]["#title"])) {
    $vars["label"] = "Posted:";
    $vars["body"] = $variables["content"]["field_published_date"];
    $variables["content"]["field_published_date"] = Drupal::theme()
      ->render("detail_item", $vars);
  }
  else {
    unset($variables["content"]["field_published_date"]);
  }

  // Render the field_multiple_neighborhoods into a details_item.
  if (isset($variables["content"]["field_multiple_neighborhoods"]["#items"])) {
    $vars["label"] = $variables["content"]["field_multiple_neighborhoods"]["#title"] . ":";
    $vars["body"] = $variables["content"]["field_multiple_neighborhoods"];
    $variables["content"]["field_multiple_neighborhoods"] = Drupal::theme()
      ->render("detail_item", $vars);
  }
  else {
    unset($variables["content"]["field_multiple_neighborhoods"]);
  }

  // Render the downloads (field_links) into a details_item.
  if (isset($variables["content"]["field_links"]["#title"])) {
    $vars["label"] = $variables["content"]["field_links"]["#title"] . ":";
    $vars["body"] = $variables["content"]["field_links"];
    $variables["content"]["field_links"] = Drupal::theme()
      ->render("detail_item", $vars);
  }
  else {
    unset($variables["content"]["field_links"]);
  }

  // Check for cancelled state.
  $node = $variables['elements']['#node'];
  if ($node->hasField("field_cancelled")) {
    $variables["is_cancelled"] = ($node->field_cancelled->value == "1");
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_event_preprocess_field__field_address(&$variables) {
  // Hide the country field in the address.
  if ($variables["element"]["#bundle"] != "event") {
    return;
  }
  if (isset($variables["items"])) {
    foreach ($variables["items"] as $key => &$item) {
      $item["content"]["country"]["#attributes"]["class"][] = "hidden";
    }
  }
}
