id: node__department_profile
label: 'Node: Department Profile'
migration_group: bos_nodes
migration_tags:
  - Drupal 7
  - Content
dependencies:
  enforced:
    module:
      - bos_migration
source:
  plugin: d7_node
  node_type: department_profile
  track_changes: true
process:
  langcode:
    plugin: default_value
    source: language
    default_value: "en"
  title: title
  uid: node_uid
  status: status
  body: body
  created: created
  changed: changed
  promote: promote
  sticky: sticky
  revision_uid: revision_uid
  revision_log: log
  revision_timestamp: timestamp
  field_components: field_components
  field_icon: field_icon
  field_department_type: field_department_type
  field_email: field_email
  field_hide_contact_form: field_hide_contact_form
  field_intro_text: field_intro_text
  field_operation_hours: field_operation_hours
  field_phone_number: field_phone_number
  field_published_date: field_published_date
  field_sidebar_components: field_sidebar_components
  field_updated_date: field_updated_date
  field_address:
      plugin: addressfield
      source: field_address
destination:
  plugin: 'entity:node'
  default_bundle: department_profile
  new_revisions: true
migration_dependencies:
  required:
  - d7_user
  - d7_node_type
  optional:
  - d7_field_instance
  - d7_comment_field_instance
