id: node_revision__change
label: 'Node_revision: Change'
migration_group: bos_nodes
audit: true
migration_tags:
  - Drupal 7
  - Content
source:
  plugin: d7_node_revision
  node_type: change
process:
  langcode:
    plugin: default_value
    source: language
    default_value: "en"
  title: title
  uid: node_uid
  status: status
  created: created
  changed: changed
  promote: promote
  sticky: sticky
  revision_uid: revision_uid
  revision_log: log
  revision_timestamp: timestamp
destination:
  plugin: entity_revision:node
  default_bundle: change
migration_dependencies:
  required:
    - node__change
