<?php

/**
 * @file
 * The Base module file for bos_grid module.
 */

use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_theme().
 */
function bos_grid_theme() {
  return [
    'paragraph__grid_of_topics' => [
      'base hook' => 'paragraph',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'paragraph__grid_of_people' => [
      'base hook' => 'paragraph',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'paragraph__grid_of_places' => [
      'base hook' => 'paragraph',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'paragraph__grid_of_programs_initiatives' => [
      'base hook' => 'paragraph',
    ],
    'node__topic_page__listing' => [
      'base hook' => 'node',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'node__person_profile__listing' => [
      'base hook' => 'node',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'node__place_profile__listing' => [
      'base hook' => 'node',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'field__field_email__mode__listing' => [
      'base hook' => 'field',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
    'field__field_phone_number__mode__listing' => [
      'base hook' => 'field',
      'path' => drupal_get_path('module', 'bos_grid') . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_grid_preprocess_field(&$variables, $hook) {
  if ($variables["field_name"] == "field_person_photo"){
    if (isset($variables["element"]["#object"]) && $variables["element"]["#object"]->bundle() == "quote") {
      return;
    }
    $variables['items'][0]['content']['#item_attributes']['class'] = "cdp-i";
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function bos_grid_preprocess_paragraph(&$vars) {
  if (!empty($vars['paragraph'])) {
    $paragraph = $vars['paragraph'];
    switch ($paragraph->bundle()) {
      case 'grid_of_programs_initiatives':
      case 'grid_of_people':
      case 'grid_of_places':
        $theme = $paragraph->get('field_component_theme')->getValue()['0']['value'];
        $vars['attributes']['class'][] = 'b--' . !empty($theme) ? $theme : 'g';
        $vars['section_header_theme'] = $theme === 'b' ? 'sh--w' : '';
        break;
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function bos_grid_preprocess_node(&$vars) {
  // TODO: This wont be called for anything except nodes defined in the
  // hook_theme of this module ...
  if (!empty($vars['elements']['node']) && $vars['elements']['#view_mode'] == 'listing') {
    $node = $vars['elements']['#node'];
    switch ($node->bundle()) {
      case 'topic_page':
        $vars['title_raw'] = $node->getTitle();
        break;

      case 'place_profile':
        $vars['short_title'] = Unicode::truncate($node->getTitle(), 50, TRUE, TRUE, 1);
        if (!$node->get('field_intro_image')->isEmpty()) {
          $base_url = file_load($node->get('field_intro_image')->getValue()['0']['target_id'])->getFileUri();
          $style = \Drupal::entityTypeManager()->getStorage('image_style')->load('grid_card_image');
          $vars['image'] = $style->buildUrl($base_url);
        }
        break;
    }
  }
}
