<?php

/**
 * @file
 * The Base module file for bos_external_link module.
 */

/**
 * Implements hook_theme().
 */
function bos_external_link_theme() {
  $theme['paragraph__external_link'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_external_link/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_field().
 */
function bos_external_link_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'field_external_link' && $object = $vars['element']['#object']) {
    if (is_a($object, 'Drupal\paragraphs\Entity\Paragraph') && $object->bundle() == 'external_link') {
      if ($object->getParentEntity()->bundle() == 'fyi') {
        $vars['items'][0]['content']['#options']['attributes']['class'][] = 'fyi-l lnk-e';
      }
    }
  }
}
