adding:
  tags:
    robots: 'noindex, nofollow, noarchive, noimageindex'
    canonical_url: 'https://d8-stg.boston.gov[current-page:url:path]'
removing:
  tags:
    google-site-verification: Do93qJZE2c5ibJnBWowjyjeIzVD6he_ZSCJU2J6eHn8
