_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: mime_mail
  formatter: mime_mail
modules:
  bos_email:
    none:
      sender: mime_mail
      formatter: mime_mail
