_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: 'Ping Logins'
logout_menu_item_title: Logout
login_redirect_url: '<front>'
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: true
logout_different_user: false
drupal_login_roles:
  administrator: administrator
  site_administrator: site_administrator
  developer: developer
  authenticated: '0'
  content_editor: '0'
  content_reviewer: '0'
  content_author: '0'
  metrolist_editor: '0'
  election_editor: '0'
sp_entity_id: d10test
sp_name_id_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
sp_x509_certificate: ''
sp_new_certificate: ''
sp_private_key: ''
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: 'urn:test:sso:boston.gov'
idp_single_sign_on_service: 'https://sso-test.boston.gov/idp/ssp.saml2'
idp_single_log_out_service: 'https://sso-test.boston.gov/idp/startSLO.ping'
idp_change_password_service: 'https://access-test.boston.gov/change-password'
idp_certs:
  - MIIH5zCCBc+gAwIBAgITFgAAARQ87oIbI0l/uQAAAAABFDANBgkqhkiG9w0BAQsFADBwMRMwEQYKCZImiZPyLGQBGRYDY29iMRYwFAYKCZImiZPyLGQBGRYGYm9zdG9uMRgwFgYKCZImiZPyLGQBGRYIY2l0eWhhbGwxJzAlBgNVBAMTHkNpdHlPZkJvc3Rvbi1FbnRlcnByaXNlLVN1Yi1DQTAeFw0xODA2MTIxNzEzMzVaFw0yMTA2MTExNzEzMzVaMIGAMQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUExDzANBgNVBAcTBkJvc3RvbjEVMBMGA1UEChMMQ2l0eU9mQm9zdG9uMRIwEAYDVQQLEwlJQU1TU09TU0wxKDAmBgNVBAMTH3p0cGluZ2ZlZDAxLmNpdHloYWxsLmJvc3Rvbi5jb2IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCCente0fJHblaXUmUZBYn1V9ZER70MWmDZaomlS3OYTHD5r11Pajfmx8Eao/QmH/npozNHM/vNcoRNJJD2WyQoJXsOVL1vzPeaV2wHHosbO2LTgVWjYKQscbXi0PsGmSloKb5odF97V7hiQCzdXa8DVzvsLZnxvRcFdk9hYzJKedzsilfpQlCWJ033wBw5moO5aWM8sTt0+/DB6KEIN+9GAeVFdO3abIrxRn5vTU8ZKWHp8apE54m6vKxGxgkznXx47WddlL4qwMeiE8IgRcf1Fyi0At+hREEc2jzx91R3BZOIUBPOeOFVGiOK/t5ypXzqj6qlkVtXHy5aUW8fsK6pAgMBAAGjggNnMIIDYzAdBgNVHQ4EFgQUKLvkwVQFmAc3X0dS28xUqHIjw4IwKgYDVR0RBCMwIYIfenRwaW5nZmVkMDEuY2l0eWhhbGwuYm9zdG9uLmNvYjAfBgNVHSMEGDAWgBQMhqe6KaerD/L6eOCkI0/igJXFtjCCASsGA1UdHwSCASIwggEeMIIBGqCCARagggEShoHKbGRhcDovLy9DTj1DaXR5T2ZCb3N0b24tRW50ZXJwcmlzZS1TdWItQ0EsQ049WlBDT0JTQ0FBUFAwMSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1ib3N0b24sREM9Y29iP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludIZDaHR0cDovL2NybC5ib3N0b24uY29iL0NlcnRFbnJvbGwvQ2l0eU9mQm9zdG9uLUVudGVycHJpc2UtU3ViLUNBLmNybDCCAUQGCCsGAQUFBwEBBIIBNjCCATIwgbwGCCsGAQUFBzAChoGvbGRhcDovLy9DTj1DaXR5T2ZCb3N0b24tRW50ZXJwcmlzZS1TdWItQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9Ym9zdG9uLERDPWNvYj9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTBxBggrBgEFBQcwAoZlaHR0cDovL2FpYS5ib3N0b24uY29iL0NlcnRFbnJvbGwvWlBDT0JTQ0FBUFAwMS5jaXR5aGFsbC5ib3N0b24uY29iX0NpdHlPZkJvc3Rvbi1FbnRlcnByaXNlLVN1Yi1DQS5jcnQwDgYDVR0PAQH/BAQDAgWgMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIbngF6G3J5Ph5mbJoX05xKFzJdQX4vraYfs+28CAWQCAQowEwYDVR0lBAwwCgYIKwYBBQUHAwEwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAgEAQgmFGc/DnlMeLeAKdI88eJHovJ5Ch5uQYVMQ4PqHTpNPQbte3y2Jt3VFQHUz+BIYOIeTwDL/9XK5AQ7TcAU+ncljH93ChtA/YCkjZRdl1ykyQ/OGWenjCdvlI9UUlXMmMEXu7+5/nGyrhPEYyxgSGRy4VaSL09tHPK+ZLSpzdaaFcEDiUVrYHCnslhEPBpor6KsbWNAjqEJ8hLicofQEarVkNrgiTeCaepBlwSocN+NKcrpGCjvZvYwoUaFfB7oIrpjQYF9btkg0Om4WW5n23zT2eHnzJGb1MYjIXN3YTi+zEbGbuGl8y1lPkJMCi/lAuGBVxdkruLHdZTCFSwKouWueCOZvKTBo3/WhMr+h0WZ5x2wLOYzMpcEsvCsyxkgUAH7KUrvwr2CG7cTAf/vO5SZTbHZO0TUvU/CNKCMjmpcLIWOaTFhRJ3cVJ9KcuXadldN0HQUekr9vR3W20QIGYK5Y+NVwm1G4EvLG518nlk034HeXi6An89nZ0cHfe6v4tEpeyrxuctHxj3YzUN/guOAsQMvkvip/S3FZ3zJXyJW6AkQpMKubJzNURA6E/gM/LSVaJdtGATk+oW0Fn0VLCmjH/JuIrS6k93lbt4719zzl9wxNPNP6Y25I/oH6pVrfnxNiIPCT+CudWpXVVR7/UkhlSXnd+NqnscD9tVk/qVI=
idp_cert_encryption: ''
unique_id_attribute: uid
map_users: false
map_users_name: true
map_users_mail: true
map_users_roles:
  content_editor: content_editor
  content_reviewer: content_reviewer
  content_author: content_author
  metrolist_editor: metrolist_editor
  election_editor: election_editor
  administrator: '0'
  site_administrator: '0'
  developer: '0'
create_users: true
sync_name: true
sync_mail: true
user_name_attribute: uid
user_mail_attribute: email
request_set_name_id_policy: false
strict: true
security_metadata_sign: false
security_authn_requests_sign: false
security_logout_requests_sign: false
security_logout_responses_sign: false
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: true
security_assertions_signed: false
security_assertions_encrypt: false
security_nameid_encrypted: false
security_want_name_id: false
security_request_authn_context: false
security_lowercase_url_encoding: false
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: true
debug_log_in: true
debug_log_saml_in: true
debug_log_saml_out: true
debug_phpsaml: true
use_proxy_headers: false
use_base_url: true
realname: 'given_name sn'
roles:
  administrator: administrator
  site_administrator: site_administrator
