_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: false
auth_source: default-sp
login_link_display_name: 'Federated login'
login_link_show: true
user_name: eduPersonPrincipalName
unique_id: eduPersonPrincipalName
mail_attr: mail
header_no_cache: false
role:
  population: null
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles: {  }
  default_login_users: '1'
logout_goto_url: null
user_register_original: admin_only
sync:
  mail: true
  user_name: true
autoenablesaml: false
debug: false
secure: false
httponly: false
