<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function node_elections_theme($existing, $type, $theme, $path) {
  return [
    'node__election_report__election_card' => [
      'base hook' => 'node',
    ],
    'paragraph__election_area_results__election_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__election_contest_results__election_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__election_card_full' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__election_candidate_results__election_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__election_card__full' => [
      'base hook' => 'paragraph',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_selections_preprocess_node(&$variables, $a) {

  if (isset($variables["node"]) && in_array($variables["node"]->bundle(), [
      "election_report",
      "node_election_uploader",
    ])) {
    $variables['#attached']['library'][] = 'node_elections/election';
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_elections_preprocess_node(&$variables, $a) {

  if (isset($variables["node"]) && in_array($variables["node"]->bundle(), [
      "election_report",
    ])) {
    $variables['#attached']['library'][] = 'node_elections/election';
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_elections_preprocess_paragraph(&$variables) {
  if (isset($variables["paragraph"]) && in_array($variables["paragraph"]->bundle(), [
    'election_area_results'
  ])) {
  }
}

/**
 * Implements hook_form_alter().
 */
function node_elections_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, [
    "node_election_report_form",
    "node_election_report_edit_form",
  ])) {
    $form["#attached"]["library"][] = 'node_elections/election_admin';
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function node_elections_field_widget_complete_entity_reference_autocomplete_form_alter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  // Store Contextual Variable info in the seesion object.
  // We know this is ONLY used by an authenticated user, who will therefore
  //  have their own session.
  switch($field_widget_complete_form["widget"]["#field_name"]){
    case "field_election_area":
      $tmp = \Drupal::service("tempstore.private")->get("node_elections");
      $tmp->set("nid", $form_state->getFormObject()->getEntity()->id());
      break;
    case "field_election_contest":
      $tmp = \Drupal::service("tempstore.private")->get("node_elections");
      $tmp->set("nid", $form_state->getFormObject()->getEntity()->id());
      $tmp->set("tid", $field_widget_complete_form["widget"][0]["target_id"]["#default_value"]->id());
      break;
  }
}

/**
 * Implements hook_views_pre_build().
 */
function node_elections_views_pre_build(ViewExecutable $view) {
  if ($view->id() == "election_reports_2022") {
    switch ($view->current_display) {
      case "elections_autocomplete":
        break;
      case "election_contest_autocomplete":
      case "election_area_autocomplete":
        $tmp = \Drupal::service("tempstore.private")->get("node_elections");
        $view->setArguments([$tmp->get("nid")]);
        break;
      case "election_candidate_autocomplete":
        $tmp = \Drupal::service("tempstore.private")->get("node_elections");
        $view->setArguments([$tmp->get("nid"), $tmp->get("tid")]);
        break;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_elections_preprocess_taxonomy_term(&$variables) {
  if (isset($variables["term"]) && in_array($variables["term"]->bundle(), [
      "elections",
      "election_areas",
      "elector_groups",
      "election_candidates",
      "election_contests",
    ])) {
    $variables['#attached']['library'][] = 'node_elections/election';
  }
}

/**
 * Implements hook_paragraph_HOOK_summary_alter().
 */
function node_elections_paragraph_election_area_results_summary_alter(array $form_widget, array $para, array $attributes) {
  // TODO: (optionally) Add some summary text here for the elections paragraphs.
}

/**
 * Implements hook_form_ID_alter().
 */
function node_elections_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $form_state) {

  switch ($form_state->getBuildInfo()["args"][0]->get("name")) {
    case "Elections":
      $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
        [t('Election Date')],
        array_slice($form['terms']['#header'], 1, NULL, TRUE));
      foreach ($form['terms'] as &$term) {
        if (is_array($term) && !empty($term['#term'])) {
          $election = $term['#term']->field_election_date->value;
          $status['date'] = [
            '#markup' => $election,
            '#type' => 'item',
          ];

          $term = array_slice($term, 0, 1, TRUE) +
            $status +
            array_slice($term, 1, NULL, TRUE);
        }
      }
      break;

    case "Elector Groups":
      $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
        [t('Election')],
        array_slice($form['terms']['#header'], 1, NULL, TRUE));
      foreach ($form['terms'] as &$term) {
        if (is_array($term) && !empty($term['#term'])) {
          $election_term_id = $term['#term']->field_election->target_id;
          $field =[
            "#markup" => "<b>** Orphan</b>",
            "#type" => "item",
          ];
          if ($election_term = Term::load($election_term_id)) {
            $election = $election_term->getName();
            $field = [
              '#title' => $election,
              '#url' => Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $election_term_id]),
              '#type' => 'link',
            ];
          }
          $status['election'] = $field;

          $term = array_slice($term, 0, 1, TRUE) +
            $status +
            array_slice($term, 1, NULL, TRUE);
        }
      }
      break;

    case "Election Areas":
      $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
        [t('Election')],
        array_slice($form['terms']['#header'], 1, NULL, TRUE));
      foreach ($form['terms'] as &$term) {
        if (is_array($term) && !empty($term['#term'])) {
          $election_term_id = $term['#term']->field_election->target_id;
          $field =[
            "#markup" => "<b>** Orphan</b>",
            "#type" => "item",
          ];
          if ($election_term = Term::load($election_term_id)) {
            $election = $election_term->getName();
            $field = [
              '#title' => $election,
              '#url' => Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $election_term_id]),
              '#type' => 'link',
            ];
          }
          $status['election'] = $field;

          $term = array_slice($term, 0, 1, TRUE) +
            $status +
            array_slice($term, 1, NULL, TRUE);
        }
      }
      break;

    case "Election Contests":
      $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
        [t('Election')],
        array_slice($form['terms']['#header'], 1, NULL, TRUE));
      foreach ($form['terms'] as &$term) {
        if (is_array($term) && !empty($term['#term'])) {
          $field = [
            "#markup" => "<b>** Orphan</b>",
            "#type" => "item",
          ];
          $election_term_id = $term['#term']->field_election->target_id;
          if ($election_term = Term::load($election_term_id)) {
            $election = $election_term->getName();
            $field = [
              '#title' => $election,
              '#url' => Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $election_term_id]),
              '#type' => 'link',
            ];
          }

          $status['election'] = $field;

          $term = array_slice($term, 0, 1, TRUE) +
            $status +
            array_slice($term, 1, NULL, TRUE);
        }
      }
      break;

    case "Election Candidates":
      $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
        [t('Election')],
        array_slice($form['terms']['#header'], 1, NULL, TRUE));
      foreach ($form['terms'] as &$term) {
        if (is_array($term) && !empty($term['#term'])) {
          $field = [
            "#markup" => "<b>** Orphan</b>",
            "#type" => "item",
          ];
          $contest_term_id = $term['#term']->field_contest->target_id;
          if ($contest_term = Term::load($contest_term_id)) {
            $election_term_id = $contest_term->field_election->target_id;
            $election_term = Term::load($election_term_id);
            $election = $election_term->getName();
            $field = [
              '#title' => $election,
              '#url' => Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $election_term_id]),
              '#type' => 'link',
            ];
          }

          $status['election'] = $field;

          $term = array_slice($term, 0, 1, TRUE) +
            $status +
            array_slice($term, 1, NULL, TRUE);
        }
      }
      break;
  }

}
