<?php

/**
 * @file
 * Code for the Boston Component Cabinet feature.
 */

/**
 * Implements hook_preprocess_HOOK__TYPE().
 */
function bos_cabinet_preprocess_paragraph__cabinet(&$variables) {
}

/**
 * Implements hook_theme().
 */
function bos_cabinet_theme() {
  $theme = [
    'paragraph__cabinet__full' => [
      'base hook' => 'paragraph',
    ],
    'field__field_email__mode__embed' => [
      'base hook' => 'field',
    ],
    'field__field_phone_number__mode__embed' => [
      'base hook' => 'field',
    ],
  ];
  return $theme;
}
