<?php

/**
 * @file
 * The Base module file for bos_iframe module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function bos_iframe_theme() {
  $theme['paragraph__iframe'] = [
    'base hook' => 'paragraph',
    'path' => drupal_get_path('module', 'bos_iframe') . '/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_paragraph().
 */
function bos_iframe_preprocess_paragraph(&$vars) {
  if (!empty($vars['paragraph'])) {
    $paragraph = $vars['paragraph'];
    switch ($paragraph->bundle()) {
      case 'iframe':
        if (!$paragraph->get('field_source_url')->isEmpty()) {
          $url = $paragraph->get('field_source_url')->getValue();
          $vars['source_url'] = $url['0']['value'];
        }
        $vars['id'] = Html::getUniqueId('iframe');
        if (!$paragraph->get('field_iframe_size')->isEmpty()) {
          $size = $paragraph->get('field_iframe_size')->getValue()['0']['value'];
          $vars['size'] = !empty($size) ? "height: {$size}px;" : NULL;
        }
        break;
    }
  }
}
