<?php

/**
 * @file
 * Primary module hooks for bos_transaction_grid module.
 *
 */

/**
 * Implements hook_theme().
 */
function bos_transaction_grid_theme() {
  return [
    'paragraph__transaction_grid' => [
      'base hook' => 'paragraph',
      'path' => 'modules/custom/bos_components/modules/bos_transaction_grid/templates',
      'template' => 'paragraph--transaction-grid',
    ],
    'field__paragraph__field_transactions' => [
      'base hook' => 'paragraph',
      'path' => 'modules/custom/bos_components/modules/bos_transaction_grid/templates',
      'template' => 'field--paragraph--field-transactions',
    ],
  ];
}
