<?php

/**
 * @file
 * Provides a guide entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function topic_page_theme() {
  return [
    'guide' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for guide templates.
 *
 * Default template: guide.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the guide information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_guide(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
