<?php

/**
 * @file
 * The Base module file for bos_upcoming_events module.
 */

/**
 * Implements hook_theme().
 */
function bos_upcoming_events_theme() {
  $theme['paragraph__upcoming_events'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_upcoming_events/templates',
  ];
  $theme['views_view_fields__upcoming_events'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_upcoming_events/templates',
  ];
  $theme['views_view_unformatted__upcoming_events'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_upcoming_events/templates',
  ];
  return $theme;
}
