<?php

use Drupal\Core\Render\Markup;

/**
 * Implements hook_theme().
 */
function bos_webform_theme() {
  $theme['paragraph__cob_webform_component'] = [
    'base hook' => 'paragraph',
  ];
  $theme['webform_actions__cob_webform_component'] = [
    'base hook' => 'webform_actions',
  ];
  $theme['input__cob_webform_component'] = [
    'template' => 'input--cob-webform-component'
  ];
  $theme['webform_progress_tracker__cob_webform_component'] = [
    'base_hook' => 'webform_progress_tracker'
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_webform_preprocess_paragraph__cob_webform_component(&$variables) {
  $variables['#attached']['library'][] = 'bos_webform/patterns.overrides';
  $variables['#attached']['library'][] = 'bos_webform/patterns.extensions';
  $variables['#attached']['library'][] = 'webform/libraries.progress-tracker';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bos_webform_theme_suggestions_webform_actions_alter(array &$suggestions, array $variables) {
  $suggestions[] = "webform_actions__cob_webform_component";
}

function bos_webform_theme_suggestions_webform_progress_tracker_alter(array &$suggestions, array $variables) {
  $suggestions[] = "webform_progress_tracker__cob_webform_component";
}

/**
 * Implements hook_paragraph_hook_summary_alter().
 */
function bos_webform_paragraph_cob_webform_component_summary_alter(array $form_widget, array $para, array $attributes) {
  // Add attributes to the summary area.
  // Set the summary content.
  $markup[] = Markup::create("Webform");
  if ($para["entity"]->hasField("field_webform_component")) {
    $markup[] = Markup::create($para["entity"]->get("field_webform_component")[0]->target_id);
  }

  return [
    'attributes' => $attributes,
    'content' => $markup,
  ];
}

/**
* Prepares variables for webform 'wizard' progress tracker templates.
 *
 * Default template: webform-progress-tracker.html.twig.
 *
 * @param array $variables
  *   An associative array containing the following key:
 *   - webform: A webform.
 *   - current_page: The current wizard page.
 */
function bos_webform_preprocess_webform_progress_tracker__cob_webform_component(array &$variables) {
  include_once DRUPAL_ROOT . "/modules/contrib/webform/includes/webform.theme.template.inc";
  _template_preprocess_webform_progress($variables);
}
