public_notice.public_notice_type.*:
  type: config_entity
  label: 'Public Notice type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
