<?php

/**
 * @file
 * The Base module file for bos311 module.
 */

/**
 * Implements hook_theme().
 */
function bos_311_theme() {
  $theme['paragraph__bos311__default'] = [
    'base hook' => 'paragraph',
  ];
  $theme['paragraph__bos311__full'] = [
    'base hook' => 'paragraph',
  ];
  $theme['field__field_311_request'] = [
    'base hook' => 'field',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_311_preprocess_paragraph__bos311__full(&$variables) {
  _bos_components_fix_attributes($variables);
  $variables['attributes']->addClass("b");
  $variables['attributes']->addClass("b--fw");
  $variables['attributes']->addClass("b--b");
  $variables['attributes']->addClass("b--by");
}
