<?php

/**
 * @file
 * The Base module file for bos_how_to_tab module.
 */

/**
 * Implements hook_theme().
 */
function bos_how_to_tab_theme() {
  $theme['node__how_to'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['field__field_how_to_tabs'] = [
    'base hook' => 'field',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_contact_step'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_tab'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_text_step'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_how_to_tab_preprocess_node(&$variables) {
  if ($node = $variables['node']) {
    $type = $node->getType();
    if ($type == 'how_to') {
      $field_how_to_tabs = $node->get('field_how_to_tabs');
      $tabs = $field_how_to_tabs->referencedEntities();
      $tab_count = count($tabs);
      $variables['how_to_tabs_count'] = $tab_count;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK__TYPE().
 */
function bos_how_to_tab_preprocess_paragraph__how_to_tab(&$variables) {
  $steps = $variables['elements']['field_how_to_steps']['#items'];
  $steps_list = $steps->referencedEntities();
  if (!empty($steps_list)) {
    $step_count = count($steps_list);
    $variables['how_to_step_count'] = $step_count;
  } else {
    $variables['how_to_step_count'] = 0;
  }
}
