<?php

/**
 * @file
 * The Base module file for bos_how_to_tab module.
 */

/**
 * Implements hook_theme().
 */
function bos_how_to_tab_theme() {
  $theme['node__how_to'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['field__field_how_to_tabs'] = [
    'base hook' => 'field',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_contact_step'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_tab'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  $theme['paragraph__how_to_text_step'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_how_to_tab/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK.
 */
function bos_how_to_tab_preprocess_paragraph(&$variables) {

  $paragraph = $variables['elements']['#paragraph'];
  $paragraph_type = $paragraph->getType();
  if ($paragraph_type == 'how_to_tab') {
    static $tabs_counter;
    $variables['how_to_tabs_count'] = ++$tabs_counter;
  } 
  else if ($paragraph_type == 'how_to_text_step' || $paragraph_type =='how_to_contact_step') {
    static $steps_counter;
    static $previous_tab_count;
    static $tabs_counter;
    if ($previous_tab_count < $tabs_counter) {
      $steps_counter = 0;
      $previous_tab_count = $tabs_counter;
    }
    $variables['how_to_step_count'] = ++$steps_counter;
    
  }

}