<?php

/**
 * @file
 * The Base module file for bos_link module.
 */

/**
 * Implements hook_theme().
 */
function bos_link_theme() {
  $theme['paragraph__external_link'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_link/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_field().
 */
function bos_link_preprocess_field(&$vars) {
  switch ($vars['element']['#field_name']) {
    case 'field_external_link':
      $vars['items'][0]['content']['#options']['attributes']['class'][] = 'lnk-e';
      if ($object = $vars['element']['#object']) {
        if (is_a($object, 'Drupal\paragraphs\Entity\Paragraph') && $object->bundle() == 'external_link' && $object->getParentEntity()->bundle() == 'fyi') {
          $vars['items'][0]['content']['#options']['attributes']['class'][] = 'fyi-l';
        }
      }
      break;
  }
}
