# ZenCity free-form

###
# @name free-form
POST {{url}}/api/mario/integrations/free-form?
  jurisdictionId={{key}}
Content-Type: application/json

{
  "submissions": [
    {
      "serial_number": "24324"
    }
  ]
}

