auth_token: Au47a8x38E
last_mnl_update: |-

  [1] Queue Process Results:<br>
  Completed at: 2021-12-19 05:04:19 UTC<br>
  == Start Condition ==================<br>
  Entities in DB at start:       400,484<br>
  Cache (unique SAM's) at start: 400,484<br>
  mnl_update queue at start:     234,173<br>
  == Queue Processing =================<br>
  New entities created:          0<br>
  Updated entities:              234,172<br>
  Unchanged entities:            1<br>
  Duplicate SAM ID's found:      0<br>
  == Result ===========================<br>
  Entities processed:            234,173<br>
  Entities in DB at end:         400,484<br>
  Cache (unique SAM's) at end:   400,484<br>
  mnl_update queue at end:       0<br>
  == Runtime ==========================<br>
  processing time: 01:04:15<br>
last_mnl_import: |-

  [1] Queue Process Results:<br>
  Completed at: 2022-01-02 06:05:04 UTC<br>
  == Start Condition ==================<br>
  Entities in DB at start:       400,484<br>
  Cache (unique SAM's) at start : 400,484<br>
  mnl_import queue at start:     799,174<br>
  == Queue Processing =================<br>
  New entities created:          0<br>
  Updated entities:              0<br>
  Unchanged entities:            27,490<br>
  Entities sent to be cleaned:   0<br>
  Duplicate SAM ID's found:      0<br>
  == Result ===========================<br>
  Entities processed:            27,490<br>
  Entities in DB at end:         400,484<br>
  Cache (unique SAM's) at end:   400,484<br>
  mnl_import queue at end:       771,685<br>
  mnl_cleanup queue at end:      174,003<br>
  == Runtime ==========================<br>
  processing time: 00:05:01<br>
last_mnl_cleanup: |-

  [2] Queue Process Results:<br>
  Completed at: 2021-03-02 16:30:05 UTC<br>
  == Start Condition ==================<br>
  Entities in DB at start:      399,552<br>
  mnl_cleanup queue at start:   349,552<br>
  == Queue Processing =================<br>
  Removed out of date entities:           175,550<br>
  Removed duplicate entities:             0<br>
  == Result ===========================<br>
  Entities in DB at end:        224,002<br>
  mnl_cleanup queue at end:     174,003<br>
  == Runtime ==========================<br>
  processing time: 08:30:00<br>