<?php

/**
 * @file
 * The install file for bos_featured_topics module.
 */

/**
 * Implements hook_uninstall().
 */
function bos_featured_topics_uninstall() {
  if (function_exists("_bos_core_uninstall_boston")) {
    _bos_core_uninstall_boston(basename(__FILE__, ".install"));
  }
}

/**
 * Implements hook_install().
 */
function bos_featured_topics_install() {
  // Copy icons into expected location.
  _bos_core_install_icons(basename(__FILE__, ".install"));
}
