<?php

/**
 * @file
 * The Base module file for bos_featured_topics module.
 */

/**
 * Implements hook_theme().
 */
function bos_featured_topics_theme() {
  $theme['paragraph__featured_topics'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_featured_topics/templates',
  ];
  $theme['node__topic_page__featured_topics'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_featured_topics/templates',
  ];
  $theme['field__component__field_title'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_featured_topics/templates',
  ];
  $theme['field__component__field_topics'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_featured_topics/templates',
  ];
  return $theme;
}
