<?php

/**
 * @file
 * Provides a script page entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function script_page_theme() {
  return [
    'script_page' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for script page templates.
 *
 * Default template: script-page.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the script page information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_script_page(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
