<?php

/**
 * @file
 * The Base module file for bos_list module.
 */

/**
 * Implements hook_theme().
 */
function bos_list_theme() {
  $theme['paragraph__list'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['field__component__field_component_title'] = [
    'base hook' => 'field',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__metrolist_affordable_housing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__metrolist_affordable_housing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__bids_rfps'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__bids_rfps'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view_unformatted__departments_listing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__departments_listing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__department_profile__department_listing'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__news_landing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__news_landing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__places'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__places'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__public_notice'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__public_notice'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__status_displays'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__topic_landing_page'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__topic_landing_page'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__topic_page__listing_long'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__transactions'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__transactions'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bos_list_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form["#id"] == 'views-exposed-form-places-page-1') {
    $form['title']['#attributes']['class'] = ['sf-i-f', 'form-text'];
    $form['title']['#attributes']['placeholder'] = 'Search...';
    $form["actions"]["submit"]["#attributes"]['class'] = ['sf-i-b', 'form-submit'];
    unset($form["#info"]["filter-title"]["label"]);
  }
  if ($form["#id"] == 'views-exposed-form-transactions-page-1') {
    $form['title']['#attributes']['class'] = ['sf-i-f', 'form-text'];
    $form['title']['#attributes']['placeholder'] = 'Search transactions...';
    $form["actions"]["submit"]["#attributes"]['class'] = ['sf-i-b', 'form-submit'];
    unset($form["#info"]["filter-title"]["label"]);
  }
}

/**                                                            
 * Implements hook_preprocess_node__BUNDLE().                   
 */                                                            
function bos_list_preprocess_node(&$variables) {
  $type = $variables['node']->getType();
  if ($type == 'topic_page') {
    // Add some custom variables to the topic page template for listing_long.
    if ($variables['view_mode'] == 'listing_long') {
      $node = $variables["elements"]["#node"]; 
      $components_field = $node->get('field_components')->getValue();
      $num_components = count($components_field);
      $variables['num_components'] = 0;
      // We show three nav links, then want to denote
      // the remainder of the links for the See More link.
      if ($num_components > 3) {
        $variables['num_components'] = $num_components - 3;
      }

      $comp_entity_id_array = array();
      foreach ($components_field as $comp) {
        $comp_entity_id_array[] = $comp['value'];
      }
			// Here we need to load all the components because
			// the not all components have a short title
			// required so we do not create nav link for it.
			$components = entity_load('paragraphs_item', $comp_entity_id_array);
			if (!empty($components)) {
				$nav_links = array();
				$num_nav_links = 0;
				foreach ($components as $comp) {
					$short_title_array = field_get_items('paragraphs_item', $comp, 'field_short_title');
					if (!empty($short_title_array)) {
						$short_title = $short_title_array[0]['safe_value'];
						$short_title = strtoupper($short_title);
						$jump_link = strtolower(trim($short_title));
						$jump_link = str_replace(" ", "-", $jump_link);
						$jump_link = str_replace("&amp;", "n", $jump_link);
						$short_title = str_replace("&AMP;", "&", $short_title);
						$nav_links[] = l(
							$short_title,
							$variables['path']['alias'],
							array(
								'fragment' => $jump_link,
								'attributes' => array(
									'class' => array('scroll-link-js'),
								),
							));
						$num_nav_links++;
						// Show only the first three links.
						// After we've computed three links, break.
						if ($num_nav_links == 3) {
							break;
						}
					}
				}
				$variables['nav_links'] = $nav_links;
			}
    }
  } 
}
