<?php

/**
 * @file
 * The Base module file for bos_list module.
 */

/**
 * Implements hook_theme().
 */
function bos_list_theme() {
  $theme['paragraph__list'] = [
    'base hook' => 'paragraph',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['field__component__field_component_title'] = [
    'base hook' => 'field',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__metrolist_affordable_housing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__metrolist_affordable_housing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__bids_rfps'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__bids_rfps'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view_unformatted__departments_listing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__departments_listing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__department_profile__department_listing'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__news_landing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__news_landing'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__event__calendar_listing'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view_unformatted__calendar'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__places'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__places'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__public_notice'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__public_notice'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__public_notice__listing'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['viewfield__paragraph__field_list'] = [
    'base hook' => 'viewfield',
  ];
  $theme['views_view_unformatted__public_notice'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__topic_landing_page'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__topic_landing_page'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view_unformatted__topic_landing_page'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_view__transactions'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['views_exposed_form__transactions'] = [
    'base hook' => 'views_view',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  $theme['node__transaction__listing'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_components/modules/bos_list/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bos_list_preprocess_paragraph__list(&$variables) {
  _bos_components_fix_attributes($variables);
  if ($variables['paragraph']->field_component_theme->value == "grey" ||
    $variables['paragraph']->field_component_theme->value == "g") {
    $variables["attributes"]->addClass("b--g");
  }
  elseif ($variables['paragraph']->field_component_theme->value == "blue" ||
    $variables['paragraph']->field_component_theme->value == "b") {
    $variables["attributes"]->addClass("b--b");
  }
  elseif ($variables['paragraph']->field_component_theme->value == "w") {
    $variables["attributes"]->addClass("b--w");
  }
  else {
    $variables["attributes"]->addClass("b--w");
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bos_list_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form["#id"] == 'views-exposed-form-places-page-1') {
    $form['title']['#attributes']['class'] = ['sf-i-f', 'form-text'];
    $form['title']['#attributes']['placeholder'] = 'Search...';
    $form["actions"]["submit"]["#attributes"]['class'] = ['sf-i-b', 'form-submit'];
    unset($form["#info"]["filter-title"]["label"]);
  }
  if ($form["#id"] == 'views-exposed-form-transactions-page-1') {
    $form['title']['#attributes']['class'] = ['sf-i-f', 'form-text'];
    $form['title']['#attributes']['placeholder'] = 'Search transactions...';
    $form["actions"]["submit"]["#attributes"]['class'] = ['sf-i-b', 'form-submit'];
    unset($form["#info"]["filter-title"]["label"]);
  }
}
