### Load Rollcall Data -inline
# 1. Ensure the Taxonomies vocab_votes and vocab_districts are set up first
# 2. Set the config ("node_rollcall.settings.auth_token")
# 3. use an array of objects, where each object contains:
#       - docketId: integer unique ID for a docket
#       - docket: docket ID - note: ID not unique may be re-used between years
#       - subject: docket text being voted upon
#       - votedate: date/time of vote in fmt yyyy-mm-ddThh:nn:ss
#       - voteId: uniqueID for this vote (pk = councillor/docket)
#       - councillor: The councillor surname
#       - vote: typically Y, N, P, NP

POST {{host}}/rest/rollcall/upload
Content-Type: application/json
Authorization: Bearer 8e4fcc89-0546-404a-bcf9-52695683d960

[
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 619,
    "councillor": "Ciommo",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 620,
    "councillor": "Connolly",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 621,
    "councillor": "Consalvo",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 622,
    "councillor": "Feeney",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 623,
    "councillor": "Flaherty",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 624,
    "councillor": "LaMattina",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 625,
    "councillor": "Linehan",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 626,
    "councillor": "Murphy",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 627,
    "councillor": "Ross",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 628,
    "councillor": "Tobin",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 629,
    "councillor": "Turner",
    "vote": "Feeney"
  },
  {
    "docketId": 55,
    "docket": "0000",
    "subject": "Election of City Council President for Calendar Year 2008",
    "votedate": "2008-01-07T00:00:00",
    "voteId": 630,
    "councillor": "Yancey",
    "vote": "Feeney"
  }
]

### Load Rollcall Data -file (full sync)
# NOTES:
# 1. Ensure the Taxonomies vocab_votes and vocab_districts are set up first
# 2. Set the config ("node_rollcall.settings.auth_token")
# 3. Filepath needs to be absolute, or relative to docroot.
# 4. Can use  - start to define the start record for importing (indexed from 0)
#             - records to defne the #records to process

POST {{host}}/rest/rollcall/upload
Content-Type: application/json
Authorization: Bearer 8e4fcc89-0546-404a-bcf9-52695683d960

{
  "file": "sites/default/files/Rollcall_History_19Mar2024.json"
}

### Export Rollcall Data -file
# NOTES:
# 1. Calling without parameters will return all records in the database
# 2. Adding ?date=yyyy-mm-dd will return all dockets for meetings after that
#     date (can also use PHP relative date strings like “-5 days” etc)
# 3. Adding ?nid=1234will return all id's with a number higher than 1234

GET {{host}}/rollcall/api/v1
Content-Type: application/json
Authorization: Bearer 8e4fcc89-0546-404a-bcf9-52695683d960

{
  "file": "sites/default/files/Rollcall_History_13Dec2023.json",
  "start": 13998,
  "records": 2000
}

### Export Experiment file
GET {{host}}/rest/rollcall/experiment/json
Content-Type: application/json

### Export Experiment file csv
GET {{host}}/rest/rollcall/experiment/csv
Content-Type: application/json
