### Load Rollcall Data -inline
# Ensure the Taxonomies vocab_votes and vocab_districts are set up first
# also need to set the config ("node_rollcall.settings.auth_token")

POST https://boston.lndo.site/rest/rollcall/upload
Content-Type: application/json
Authorization: Bearer 8e4fcc89-0546-404a-bcf9-52695683d960

[
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17324,
    "councillor": "Arroyo",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17325,
    "councillor": "Baker",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17326,
    "councillor": "Breadon",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17327,
    "councillor": "Coletta",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17328,
    "councillor": "Durkan",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17329,
    "councillor": "Fernandes Anderson",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17330,
    "councillor": "Flaherty",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17331,
    "councillor": "Flynn",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17332,
    "councillor": "Lara",
    "vote": "NP"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17333,
    "councillor": "Luoijeune",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17334,
    "councillor": "Mejia",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17335,
    "councillor": "Murphy",
    "vote": "Y"
  },
  {
    "docketId": 3205,
    "docket": "0000",
    "subject": "Message and order for your approval, an Order to reduce the FY24 \r\n\tappropriation for the Reserve for Collective Bargaining by Twenty Four \r\n\tThousand One Hundred Twenty One Dollars ($24,121.00) to provide \r\n\tfunding for the Property Management Department for the FY24 increase \r\n\tcontained within the collective bargaining agreements between the City of \r\n\tBoston and the New England Police Benevolent Association.\r\n\tFiled in the Office of the City Clerk on October 30, 2023.\r\n\tThe rules were suspended; the order was passed; yeas 12.\r\n",
    "votedate": "2000-01-01T00:00:00",
    "voteId": 17336,
    "councillor": "Worrell",
    "vote": "Y"
  }
]

### Load Rollcall Data -file (full sync)
# NOTES:
# 1. Ensure the Taxonomies vocab_votes and vocab_districts are set up first
# 2. Set the config ("node_rollcall.settings.auth_token")
# 3. Filepath needs to be absolute, or relative to docroot.

POST https://boston.lndo.site/rest/rollcall/upload
Content-Type: application/json
Authorization: Bearer 8e4fcc89-0546-404a-bcf9-52695683d960

{
  "file": "sites/default/files/Rollcall_History_13Dec2023.json",
  "records": 1
}
