# @file(yaml)
# Global Configurations for Percy CLI
version: 2
snapshot:
  widths: [390,1280]
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
