- name: Article with ALL components
  url: https://d8-dev.boston.gov/departments/digital-team/test-page
  waitForTimeout: 5000

- name: Event (basic) - WEST END COMMUNITY PRESERVATION
  url: https://d8-dev.boston.gov/node/61556

- name: Event (with header) - MAYOR ON MAIN TROLLEY TOUR
  url: https://d8-dev.boston.gov/node/45361

- name: Listing Page - PAY AND APPLY
  url: https://d8-dev.boston.gov/node/32906

- name: Listing Page - PARKS AND PLAYGROUNDS
  url: https://d8-dev.boston.gov/node/32946

- name: Place Profile - ANIMAL ACRE AND CONTROL CENTER
  url: https://d8-dev.boston.gov/node/2191

- name: Place Profile - BAY VILLAGE HISTORIC DISTRICT
  url: https://d8-dev.boston.gov/node/3251

- name: Person Profile - MARK CIOMMO
  url: https://d8-dev.boston.gov/node/401

- name: Person Profile - ALEX LAWRENCE
  url: https://d8-dev.boston.gov/node/15920396

- name: Program Initiative Page - MY BROTHERS KEEPER BOSTON
  url: https://d8-dev.boston.gov/node/7396

- name: Post - BIKE SHARE
  url: https://d8-dev.boston.gov/node/1741

- name: Post - RODENT AND PEST CONTROL
  url: http://d8-dev.boston.gov/node/12806

- name: How To - CPR TRAINING
  url: https://d8-dev.boston.gov/node/3606

- name: How To - FILE FOR A PROPERTY TAX ABATEMENT
  url: https://d8-dev.boston.gov/node/12806

- name: Article - FOOD TRUCKS SCHEDULE
  url: https://d8-dev.boston.gov/node/21311

- name: Article - MAYORS OFFICE OF HOUSING
  url: https://d8-dev.boston.gov/node/2726

- name: Department - DIGITAL TEAM
  url: https://d8-dev.boston.gov/node/7536

- name: Public Notice - PUBLIC FACILITIES COMMISSION MEETING
  url: https://d8-dev.boston.gov/node/64966

- name: Public Notice - BOSTON PARKS AND RECREATION COMMISSION PUBLIC HEARING
  url: https://d8-dev.boston.gov/node/48276

