- name: digital testpage
  url: https://d8-dev.boston.gov/departments/digital-team/test-page
  waitForTimeout: 5000

- name: Event (basic)
  url: https://d8-dev.boston.gov/node/61556

- name: Event (with header)
  url: https://d8-dev.boston.gov/node/45361
