# @file(yaml)
# == GITHUB ACTION ==
# Deploy workflow for Boston.gov
# Workflow monitors pipeline branchs and is triggered on Pull Requests and Merges.
#   The action is triggered before the code reaches the stage environment, so the workflow compares screenshots taken
#   from the develop environment.
name: "Pipeline: Deploy to Acquia"
on:
  push:
    branches:
      - nothing
#  push:
#    branches:
#      - develop
#      - master
  workflow_dispatch:
