name: Boston.gov Percy Snapshot Regression Testing
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  percy_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: checkout percy files
        uses: Bhacaz/checkout-files@v2
        with:
          # Take the entire percy folder.
          files: .github/percy
          # Make sure the branch used is develop.
          branch: develop

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Percy CLI
        run: npm install --save-dev @percy/cli

      - name: Environment Outputs
        run: |
          npx @percy/cli --version
          echo $GITHUB_WORKSPACE
          ls -la "${{GITHUB_WORKSPACE}}/.github/"

#      - name: Generate Snapshots
#        run: npx @percy/cli snapshot --config percy_config.yml snapshot_config.yml
#        working-directory: $GITHUB_WORKSPACE/.github/percy/
#        env:
#          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
