place_profile.place_profile_type.*:
  type: config_entity
  label: 'Place Profile type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
