<?php

/**
 * @file
 * Provides an script_page entity type.
 */

/**
 * Implements hook_theme().
 */
function node_script_page_theme() {
  $theme['node__script_page'] = [
    'base hook' => 'node',
    'path' => 'modules/custom/bos_content/modules/node_script_page/templates',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function node_script_page_preprocess_node__script_page(&$variables) {
  _bos_content_fix_attributes($variables);
  $variables['content_attributes']->addClass("desktop-100");
  $variables['content_attributes']->addClass("script-page-components");
}
