<?php

/**
 * @file
 * Provides a procurement advertisement entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function procurement_advertisement_theme() {
  return [
    'procurement_advertisement' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for procurement advertisement templates.
 *
 * Default template: procurement-advertisement.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the procurement advertisement information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_procurement_advertisement(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
